<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
 <div><h1 class="h3 mb-1"><i class="fa-brands fa-microsoft me-2"></i>Microsoft 365 Users</h1><p class="text-muted mb-0">Import and synchronize employee identities from Microsoft Entra ID.</p></div>
 <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="/portal/users"><i class="fa-solid fa-users-gear"></i> Portal users</a><a class="btn btn-outline-primary" href="/portal/users/microsoft/access"><i class="fa-solid fa-user-shield"></i> Access mapping</a><form method="post" action="/portal/users/microsoft/preview"><?=csrf_field()?><button class="btn btn-outline-success"><i class="fa-solid fa-eye"></i> Preview sync</button></form><form method="post" action="/portal/users/microsoft/sync" onsubmit="return confirm('Synchronize all Microsoft users now?');"><?=csrf_field()?><button class="btn btn-primary"><i class="fa-solid fa-rotate"></i> Sync all</button></form></div>
</div>
<?php if(!empty($preview)):?><div class="alert alert-info"><strong>Synchronization preview:</strong> <?=e($preview['create'])?> new users and <?=e($preview['update'])?> existing users would be processed. Review the directory list below before applying the sync.</div><?php endif;?>
<?php if($error):?><div class="alert alert-danger"><strong>Graph error:</strong> <?=e($error)?><div class="small mt-1">The Entra application needs application permission <code>User.Read.All</code> or <code>Directory.Read.All</code> with admin consent.</div></div><?php endif;?>
<div class="card mb-3"><div class="card-body"><form method="get" action="/portal/users/microsoft" class="row g-2 align-items-end"><div class="col-md-8"><label class="form-label">Search Microsoft directory</label><input class="form-control" name="q" value="<?=e($search)?>" placeholder="Name or user principal name"></div><div class="col-md-4"><button class="btn btn-outline-primary w-100"><i class="fa-solid fa-magnifying-glass"></i> Search</button></div></form></div></div>
<form method="post" action="/portal/users/microsoft/import"><?=csrf_field()?>
<div class="card mb-3"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><strong>Directory users</strong><div class="d-flex gap-2"><select class="form-select form-select-sm" name="role"><option value="technician">Technician</option><option value="office">Office</option><option value="estimator">Estimator</option><option value="crew_leader">Crew leader</option><option value="administrator">Administrator</option><option value="owner">Owner</option></select><button class="btn btn-sm btn-success"><i class="fa-solid fa-file-import"></i> Import selected</button></div></div>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th><input class="form-check-input" type="checkbox" id="selectAllEntra"></th><th>Name</th><th>Account</th><th>Department / Title</th><th>Status</th><th>Portal</th><th></th></tr></thead><tbody>
<?php foreach($directoryUsers as $u):?><tr><td><input class="form-check-input entra-user-check" type="checkbox" name="object_ids[]" value="<?=e($u['id'])?>"></td><td><strong><?=e($u['name'] ?: $u['email'])?></strong><div class="small text-muted"><?=e($u['office_location'])?></div></td><td><?=e($u['email'])?><div class="small text-muted"><?=e($u['upn'])?></div></td><td><?=e($u['department'] ?: '—')?><div class="small text-muted"><?=e($u['job_title'] ?: '—')?></div></td><td><?php if($u['account_enabled']):?><span class="badge text-bg-success">Enabled</span><?php else:?><span class="badge text-bg-secondary">Disabled</span><?php endif;?></td><td><?php if($u['portal_user_id']):?><span class="badge text-bg-primary">Imported</span><div class="small text-muted"><?=e($u['portal_role'])?> / <?=e($u['portal_status'])?></div><?php else:?><span class="badge text-bg-light border">Not imported</span><?php endif;?></td><td class="text-end"><form method="post" action="/portal/users/microsoft/<?=e($u['id'])?>/sync"><?=csrf_field()?><button class="btn btn-sm btn-outline-primary" title="Synchronize this user"><i class="fa-solid fa-rotate"></i></button></form></td></tr><?php endforeach;?>
<?php if(!$directoryUsers):?><tr><td colspan="7" class="text-center text-muted py-4">No Microsoft users returned.</td></tr><?php endif;?></tbody></table></div></div></form>
<div class="card"><div class="card-header"><strong>Recent synchronization runs</strong></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Completed</th><th>Type</th><th>Created</th><th>Updated</th><th>Disabled</th><th>Errors</th></tr></thead><tbody><?php foreach($runs as $r):?><tr><td><?=e($r['completed_at'])?></td><td><?=e($r['sync_type'])?></td><td><?=e($r['created_count'])?></td><td><?=e($r['updated_count'])?></td><td><?=e($r['disabled_count'])?></td><td><?php if($r['error_count']):?><span class="badge text-bg-danger" title="<?=e($r['error_detail'])?>"><?=e($r['error_count'])?></span><?php else:?><span class="badge text-bg-success">0</span><?php endif;?></td></tr><?php endforeach;?><tr></tr></tbody></table></div></div>
<script>document.getElementById('selectAllEntra')?.addEventListener('change',e=>document.querySelectorAll('.entra-user-check').forEach(c=>c.checked=e.target.checked));</script>
