<?php
namespace App\Services;
use App\Core\Database;
use App\Core\Env;
use RuntimeException;
final class QuickBooksService
{
    public static function configured():bool{return (string)Env::get('QUICKBOOKS_CLIENT_ID','')!==''&&(string)Env::get('QUICKBOOKS_CLIENT_SECRET','')!=='';}
    public static function authorizationUrl(string $state):string{$params=http_build_query(['client_id'=>Env::get('QUICKBOOKS_CLIENT_ID'),'response_type'=>'code','scope'=>'com.intuit.quickbooks.accounting','redirect_uri'=>Env::get('QUICKBOOKS_REDIRECT_URI'),'state'=>$state]);return 'https://appcenter.intuit.com/connect/oauth2?'.$params;}
    public static function exchangeCode(string $code):array{return self::tokenRequest(['grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>Env::get('QUICKBOOKS_REDIRECT_URI')]);}
    public static function encrypt(string $value):string{$key=hash('sha256',(string)Env::get('APP_KEY','change-me'),true);$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($value,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag);if($cipher===false)throw new RuntimeException('Token encryption failed.');return base64_encode($iv.$tag.$cipher);}
    public static function decrypt(?string $value):string{if(!$value)return '';$raw=base64_decode($value,true);if($raw===false||strlen($raw)<29)throw new RuntimeException('Invalid encrypted token.');$iv=substr($raw,0,12);$tag=substr($raw,12,16);$cipher=substr($raw,28);$plain=openssl_decrypt($cipher,'aes-256-gcm',hash('sha256',(string)Env::get('APP_KEY','change-me'),true),OPENSSL_RAW_DATA,$iv,$tag);if($plain===false)throw new RuntimeException('Token decryption failed.');return $plain;}
    private static function tokenRequest(array $fields):array{$ch=curl_init('https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPAUTH=>CURLAUTH_BASIC,CURLOPT_USERPWD=>Env::get('QUICKBOOKS_CLIENT_ID').':'.Env::get('QUICKBOOKS_CLIENT_SECRET'),CURLOPT_HTTPHEADER=>['Accept: application/json','Content-Type: application/x-www-form-urlencoded'],CURLOPT_POSTFIELDS=>http_build_query($fields),CURLOPT_TIMEOUT=>30]);$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($body===false||$status>=300)throw new RuntimeException('QuickBooks token request failed: '.($body?:curl_error($ch)));return json_decode($body,true,512,JSON_THROW_ON_ERROR);}
    private static function connection():array{$row=Database::connection()->query("SELECT * FROM accounting_connections WHERE provider='quickbooks' LIMIT 1")->fetch();if(!$row||$row['status']!=='connected'||!$row['realm_id'])throw new RuntimeException('QuickBooks is not connected.');if(!$row['token_expires_at']||strtotime($row['token_expires_at'])<time()+120){$tokens=self::tokenRequest(['grant_type'=>'refresh_token','refresh_token'=>self::decrypt($row['refresh_token_enc'])]);Database::connection()->prepare("UPDATE accounting_connections SET access_token_enc=?,refresh_token_enc=?,token_expires_at=DATE_ADD(NOW(),INTERVAL ? SECOND),refresh_expires_at=DATE_ADD(NOW(),INTERVAL ? SECOND),last_error=NULL WHERE id=?")->execute([self::encrypt($tokens['access_token']),self::encrypt($tokens['refresh_token']??self::decrypt($row['refresh_token_enc'])),$tokens['expires_in']??3600,$tokens['x_refresh_token_expires_in']??8726400,$row['id']]);$row=Database::connection()->query("SELECT * FROM accounting_connections WHERE provider='quickbooks' LIMIT 1")->fetch();}return $row;}
    private static function api(string $method,string $path,?array $payload=null):array{$c=self::connection();$base=(string)Env::get('QUICKBOOKS_ENVIRONMENT','production')==='sandbox'?'https://sandbox-quickbooks.api.intuit.com':'https://quickbooks.api.intuit.com';$url=$base.'/v3/company/'.rawurlencode($c['realm_id']).'/'.ltrim($path,'/').'?minorversion=75';$ch=curl_init($url);$headers=['Authorization: Bearer '.self::decrypt($c['access_token_enc']),'Accept: application/json','Content-Type: application/json'];curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>45]);if($payload!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload,JSON_THROW_ON_ERROR));$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($body===false||$status>=300)throw new RuntimeException('QuickBooks API request failed ('.$status.'): '.($body?:curl_error($ch)));return json_decode($body,true,512,JSON_THROW_ON_ERROR);}
    public static function syncCustomer(int $id):string{$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM customers WHERE id=?');$q->execute([$id]);$c=$q->fetch();if(!$c)throw new RuntimeException('Customer not found.');$payload=['DisplayName'=>$c['display_name'],'PrimaryEmailAddr'=>['Address'=>$c['email']?:''],'PrimaryPhone'=>['FreeFormNumber'=>$c['phone']?:''],'BillAddr'=>['Line1'=>$c['billing_address']?:'']];$res=self::api('POST','customer',$payload);$remote=(string)($res['Customer']['Id']??'');if(!$remote)throw new RuntimeException('QuickBooks did not return a customer ID.');$pdo->prepare('UPDATE customers SET quickbooks_customer_id=?,quickbooks_synced_at=NOW() WHERE id=?')->execute([$remote,$id]);return $remote;}
    public static function syncInvoice(int $id):string{$pdo=Database::connection();$q=$pdo->prepare('SELECT i.*,c.quickbooks_customer_id FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.id=?');$q->execute([$id]);$i=$q->fetch();if(!$i)throw new RuntimeException('Invoice not found.');$customerId=$i['quickbooks_customer_id']?:self::syncCustomer((int)$i['customer_id']);$payload=['CustomerRef'=>['value'=>$customerId],'DocNumber'=>$i['invoice_number'],'TxnDate'=>$i['issue_date'],'DueDate'=>$i['due_date']?:$i['issue_date'],'Line'=>[['Amount'=>(float)$i['subtotal'],'DetailType'=>'SalesItemLineDetail','Description'=>'Rock Bluffs Exterior Services','SalesItemLineDetail'=>['Qty'=>1,'UnitPrice'=>(float)$i['subtotal'],'ItemRef'=>['value'=>'1']]]]];$res=self::api('POST','invoice',$payload);$remote=(string)($res['Invoice']['Id']??'');if(!$remote)throw new RuntimeException('QuickBooks did not return an invoice ID.');$pdo->prepare('UPDATE invoices SET quickbooks_invoice_id=?,quickbooks_synced_at=NOW() WHERE id=?')->execute([$remote,$id]);return $remote;}
    public static function syncPayment(int $id):string{$pdo=Database::connection();$q=$pdo->prepare('SELECT p.*,i.quickbooks_invoice_id,i.customer_id,c.quickbooks_customer_id FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=i.customer_id WHERE p.id=?');$q->execute([$id]);$p=$q->fetch();if(!$p)throw new RuntimeException('Payment not found.');$invoiceId=$p['quickbooks_invoice_id']?:self::syncInvoice((int)$p['invoice_id']);$customerId=$p['quickbooks_customer_id']?:self::syncCustomer((int)$p['customer_id']);$payload=['CustomerRef'=>['value'=>$customerId],'TotalAmt'=>(float)$p['amount'],'TxnDate'=>substr($p['received_at'],0,10),'Line'=>[['Amount'=>(float)$p['amount'],'LinkedTxn'=>[['TxnId'=>$invoiceId,'TxnType'=>'Invoice']]]]];$res=self::api('POST','payment',$payload);$remote=(string)($res['Payment']['Id']??'');if(!$remote)throw new RuntimeException('QuickBooks did not return a payment ID.');$pdo->prepare('UPDATE payments SET quickbooks_payment_id=?,quickbooks_synced_at=NOW() WHERE id=?')->execute([$remote,$id]);return $remote;}
}
