<?php
namespace App\Services;
use App\Core\Env;
final class RouteOptimizerService
{
 public static function optimize(array $jobs):array{if(count($jobs)<2)return $jobs;$provider=(string)Env::get('ROUTE_MATRIX_PROVIDER','local');if($provider!=='local'){try{return self::external($jobs,$provider);}catch(\Throwable $e){}}return self::nearestNeighbor($jobs);}
 public static function totalDistance(array $jobs):float{$total=0;for($i=1;$i<count($jobs);$i++)$total+=self::distance((float)($jobs[$i-1]['latitude']??0),(float)($jobs[$i-1]['longitude']??0),(float)($jobs[$i]['latitude']??0),(float)($jobs[$i]['longitude']??0));return round($total,2);}
 private static function nearestNeighbor(array $jobs):array{$remaining=array_values($jobs);$ordered=[array_shift($remaining)];while($remaining){$last=end($ordered);$best=0;$bestDist=PHP_FLOAT_MAX;foreach($remaining as $i=>$candidate){$d=self::distance((float)($last['latitude']??0),(float)($last['longitude']??0),(float)($candidate['latitude']??0),(float)($candidate['longitude']??0));if($d<$bestDist){$bestDist=$d;$best=$i;}}$ordered[]=$remaining[$best];array_splice($remaining,$best,1);}return $ordered;}
 private static function external(array $jobs,string $provider):array{$coords=array_map(fn($j)=>(float)$j['longitude'].','.(float)$j['latitude'],$jobs);$key=(string)Env::get('ROUTE_MATRIX_API_KEY','');$base=(string)Env::get('ROUTE_MATRIX_BASE_URL','');if($provider==='openrouteservice'){$url=($base?:'https://api.openrouteservice.org/v2/directions/driving-car/geojson');$body=['coordinates'=>array_map(fn($c)=>array_map('floatval',explode(',',$c)),$coords),'instructions'=>false];$headers=['Authorization: '.$key,'Content-Type: application/json'];}elseif($provider==='mapbox'){$url=($base?:'https://api.mapbox.com/optimized-trips/v1/mapbox/driving/').implode(';',$coords).'?source=first&roundtrip=false&access_token='.rawurlencode($key);$body=null;$headers=['Accept: application/json'];}else{return self::nearestNeighbor($jobs);}$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>30,CURLOPT_HTTPHEADER=>$headers]);if($body!==null){curl_setopt($ch,CURLOPT_POST,true);curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($body));}$raw=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($raw===false||$status>=300)throw new \RuntimeException('Routing provider failed.');$data=json_decode($raw,true,512,JSON_THROW_ON_ERROR);if($provider==='mapbox'&&!empty($data['waypoints'])){$out=[];foreach($data['waypoints'] as $w)$out[(int)$w['waypoint_index']]=$jobs[(int)$w['waypoint_index']];ksort($out);return array_values($out);}return self::nearestNeighbor($jobs);}
 private static function distance(float $lat1,float $lon1,float $lat2,float $lon2):float{if(!$lat1||!$lon1||!$lat2||!$lon2)return 9999;$r=3958.8;$dLat=deg2rad($lat2-$lat1);$dLon=deg2rad($lon2-$lon1);$a=sin($dLat/2)**2+cos(deg2rad($lat1))*cos(deg2rad($lat2))*sin($dLon/2)**2;return $r*2*atan2(sqrt($a),sqrt(1-$a));}
}
