<div class="page-title-row"><div><span class="text-muted">Intelligent operations</span><h1>ETA & Route Progress</h1><p class="text-muted mb-0">Control ETA recalculation and customer route notifications.</p></div></div>
<div class="portal-card p-4"><form method="post" action="/portal/eta-policies" class="row g-4"><?=csrf_field()?>
<div class="col-md-4"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="enabled" id="etaEnabled" <?=!empty($settings['enabled'])?'checked':''?>><label class="form-check-label" for="etaEnabled">Enable ETA processing</label></div></div>
<div class="col-md-4"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="send_on_the_way" id="etaOtw" <?=!empty($settings['send_on_the_way'])?'checked':''?>><label class="form-check-label" for="etaOtw">Send on-the-way notices</label></div></div>
<div class="col-md-4"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="send_delay_notices" id="etaDelay" <?=!empty($settings['send_delay_notices'])?'checked':''?>><label class="form-check-label" for="etaDelay">Send delay notices</label></div></div>
<div class="col-md-3"><label class="form-label">On-the-way threshold</label><div class="input-group"><input class="form-control" type="number" min="5" name="on_the_way_minutes" value="<?=e($settings['on_the_way_minutes'])?>"><span class="input-group-text">minutes</span></div></div>
<div class="col-md-3"><label class="form-label">Late threshold</label><div class="input-group"><input class="form-control" type="number" min="5" name="late_threshold_minutes" value="<?=e($settings['late_threshold_minutes'])?>"><span class="input-group-text">minutes</span></div></div>
<div class="col-md-3"><label class="form-label">Recalculation interval</label><div class="input-group"><input class="form-control" type="number" min="1" name="minimum_recalculation_minutes" value="<?=e($settings['minimum_recalculation_minutes'])?>"><span class="input-group-text">minutes</span></div></div>
<div class="col-md-3"><label class="form-label">Average route speed</label><div class="input-group"><input class="form-control" type="number" min="10" name="average_speed_mph" value="<?=e($settings['average_speed_mph'])?>"><span class="input-group-text">mph</span></div></div>
<div class="col-12"><label class="form-label">On-the-way message</label><textarea class="form-control" rows="3" name="on_the_way_template"><?=e($settings['on_the_way_template'])?></textarea><small class="text-muted">Variables: {{customer_name}}, {{job_number}}, {{eta_minutes}}, {{eta_time}}</small></div>
<div class="col-12"><label class="form-label">Delay message</label><textarea class="form-control" rows="3" name="delay_template"><?=e($settings['delay_template'])?></textarea><small class="text-muted">Variables: {{customer_name}}, {{job_number}}, {{late_minutes}}, {{eta_time}}</small></div>
<div class="col-12"><button class="btn btn-primary"><i class="fa-solid fa-floppy-disk me-2"></i>Save settings</button></div>
</form></div>
