<?php $isEdit=is_array($workflow);$action=$isEdit?'/portal/workflows/'.$workflow['id']:'/portal/workflows';?>
<div class="page-title-row"><div><span class="text-muted">Visual automation</span><h1><?=$isEdit?'Edit workflow':'Create workflow'?></h1></div><a href="/portal/workflows" class="btn btn-outline-secondary">Back</a></div>
<form method="post" action="<?=$action?>" id="workflowBuilder"><?=csrf_field()?>
<div class="row g-4"><div class="col-xl-4"><div class="portal-card p-4 sticky-xl-top" style="top:1rem"><h2 class="h5">Workflow settings</h2><div class="mb-3"><label class="form-label">Name</label><input class="form-control" name="name" required value="<?=e($workflow['name']??'')?>"></div><div class="mb-3"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="3"><?=e($workflow['description']??'')?></textarea></div><div class="mb-3"><label class="form-label">Trigger</label><select class="form-select" name="event_key"><?php foreach($catalog['events'] as $key=>$label):?><option value="<?=e($key)?>" <?=($workflow['event_key']??'')===$key?'selected':''?>><?=e($label)?></option><?php endforeach?></select></div><div class="row"><div class="col-6"><label class="form-label">Priority</label><input type="number" class="form-control" name="priority" value="<?=e($workflow['priority']??100)?>"></div><div class="col-6 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="active" <?=$isEdit?($workflow['active']?'checked':''):'checked'?>> <label class="form-check-label">Active</label></div></div></div><button class="btn btn-primary w-100 mt-4">Save workflow</button></div></div>
<div class="col-xl-8"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h4 mb-0">Workflow steps</h2><small class="text-muted">Drag cards to reorder. JSON config controls each action.</small></div><button type="button" class="btn btn-outline-primary" id="addWorkflowStep"><i class="fa-solid fa-plus"></i> Add step</button></div><div id="workflowSteps">
<?php foreach($steps as $i=>$step):?><?=workflow_step_card($i,$step,$catalog)?><?php endforeach?>
</div><div class="portal-card p-4 text-center text-muted <?=$steps?'d-none':''?>" id="workflowEmpty">Add your first action to begin the workflow.</div></div></div></form>
<?php
function workflow_step_card(int $i,array $step,array $catalog):string{ob_start();$cfg=$step['config_json']??'{}';?>
<div class="portal-card p-3 mb-3 workflow-step" draggable="true"><div class="d-flex justify-content-between align-items-center mb-3"><div><i class="fa-solid fa-grip-vertical text-muted me-2"></i><strong>Step <span class="step-number"><?=$i+1?></span></strong></div><button type="button" class="btn btn-sm btn-outline-danger remove-workflow-step"><i class="fa-solid fa-trash"></i></button></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Action</label><select class="form-select" name="step_action[]"><?php foreach($catalog['actions'] as $key=>$label):?><option value="<?=e($key)?>" <?=($step['action_key']??'')===$key?'selected':''?>><?=e($label)?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Condition</label><select class="form-select" name="step_condition[]"><?php foreach($catalog['conditions'] as $key=>$label):?><option value="<?=e($key)?>" <?=($step['condition_key']??'always')===$key?'selected':''?>><?=e($label)?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Condition field</label><input class="form-control" name="step_field[]" placeholder="invoice.balance_due" value="<?=e($step['condition_field']??'')?>"></div><div class="col-md-6"><label class="form-label">Condition value</label><input class="form-control" name="step_value[]" value="<?=e($step['condition_value']??'')?>"></div><div class="col-12"><label class="form-label">Action configuration (JSON)</label><textarea class="form-control font-monospace" rows="5" name="step_config[]"><?=e($cfg)?></textarea><div class="form-text">Examples: email recipient, SMS body, Teams title, delay minutes, or status value. Template variables such as <code>{{customer.email}}</code> are supported.</div></div></div></div>
<?php return ob_get_clean();}
?>
<template id="workflowStepTemplate"><?=workflow_step_card(0,[], $catalog)?></template>
<script src="<?=asset('js/workflow-designer.js')?>"></script>
