<div class="page-title-row"><div><span class="text-muted">Automation engine</span><h1>Workflow Designer</h1><p class="text-muted mb-0">Build event-driven automations for customer communication, operations, and collections.</p></div><a class="btn btn-primary" href="/portal/workflows/create"><i class="fa-solid fa-plus"></i> New workflow</a></div>
<div class="row g-4 mb-4">
 <?php foreach($templates as $key=>$template):?>
 <div class="col-md-6 col-xl-3"><div class="portal-card h-100 p-3"><div class="small text-uppercase text-muted mb-1">Template</div><h2 class="h6"><?=e($template['name'])?></h2><p class="small text-muted"><?=e($template['description'])?></p><form method="post" action="/portal/workflows/template"><?=csrf_field()?><input type="hidden" name="template_key" value="<?=e($key)?>"><button class="btn btn-sm btn-outline-primary">Install template</button></form></div></div>
 <?php endforeach?>
</div>
<div class="portal-card mb-4"><div class="card-header-row"><div><h2>Workflows</h2><p>Active rules and their current versions</p></div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Name</th><th>Trigger</th><th>Steps</th><th>Version</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach($rules as $r):?><tr><td><strong><?=e($r['name'])?></strong><br><small class="text-muted"><?=e($r['description']??'')?></small></td><td><code><?=e($r['event_key'])?></code></td><td><?=e($r['step_count'])?></td><td>v<?=e($r['version']??1)?></td><td><?=e($r['priority'])?></td><td><span class="badge text-bg-<?=$r['active']?'success':'secondary'?>"><?=$r['active']?'Active':'Paused'?></span></td><td><div class="d-flex gap-1 flex-wrap"><a class="btn btn-sm btn-outline-primary" href="/portal/workflows/<?=$r['id']?>/edit">Edit</a><form method="post" action="/portal/workflows/<?=$r['id']?>/toggle"><?=csrf_field()?><button class="btn btn-sm btn-outline-secondary">Toggle</button></form><form method="post" action="/portal/workflows/<?=$r['id']?>/test"><?=csrf_field()?><button class="btn btn-sm btn-outline-success">Test</button></form></div></td></tr><?php endforeach?>
<?php if(!$rules):?><tr><td colspan="7" class="text-center text-muted py-4">No workflows yet.</td></tr><?php endif?></tbody></table></div></div>
<div class="portal-card"><div class="card-header-row"><div><h2>Execution history</h2><p>Queued, running, delayed, completed, and failed runs</p></div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Rule</th><th>Entity</th><th>Step</th><th>Status</th><th>Queued</th><th>Next attempt</th><th>Error</th><th></th></tr></thead><tbody><?php foreach($runs as $r):?><tr><td><?=e($r['name'])?></td><td><?=e(($r['entity_type']?:'system').' '.($r['entity_id']?:''))?></td><td><?=e($r['current_step']??1)?></td><td><span class="badge text-bg-<?=in_array($r['status'],['completed'],true)?'success':($r['status']==='failed'?'danger':($r['status']==='running'?'primary':'warning'))?>"><?=e($r['status'])?></span></td><td><?=e($r['queued_at'])?></td><td><?=e($r['next_attempt_at']??'')?></td><td class="text-danger small"><?=e($r['error_message'])?></td><td><?php if($r['status']==='failed'):?><form method="post" action="/portal/workflows/runs/<?=$r['id']?>/retry"><?=csrf_field()?><button class="btn btn-sm btn-outline-danger">Retry</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></div>
