-- Rock Bluffs Exterior Services - Phase 19
CREATE TABLE IF NOT EXISTS user_preferences (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 preference_key VARCHAR(120) NOT NULL,
 preference_value TEXT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_user_preference(user_id,preference_key),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS dashboard_widget_preferences (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 widget_key VARCHAR(100) NOT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 is_visible TINYINT(1) NOT NULL DEFAULT 1,
 is_collapsed TINYINT(1) NOT NULL DEFAULT 0,
 width_class VARCHAR(30) NOT NULL DEFAULT 'col-xl-6',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_dashboard_widget(user_id,widget_key),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
SET @sql=IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='properties' AND COLUMN_NAME='latitude')=0,'ALTER TABLE properties ADD COLUMN latitude DECIMAL(10,7) NULL AFTER pet_notes, ADD COLUMN longitude DECIMAL(10,7) NULL AFTER latitude','SELECT 1');
PREPARE stmt FROM @sql;EXECUTE stmt;DEALLOCATE PREPARE stmt;
