<?php
$money = static fn($value): string => money((float) $value);
$percent = static fn($value): string => number_format((float) $value, 1) . '%';
$chartLabels = array_map(static fn(array $row): string => date('M Y', strtotime($row['month'] . '-01')), $monthly);
$chartInvoiced = array_map(static fn(array $row): float => (float) $row['invoiced'], $monthly);
$chartCollected = array_map(static fn(array $row): float => (float) $row['collected'], $monthly);
$serviceLabels = array_map(static fn(array $row): string => (string) $row['service'], array_slice($services, 0, 8));
$serviceRevenue = array_map(static fn(array $row): float => (float) $row['revenue'], array_slice($services, 0, 8));
$agingLabels = array_map(static fn(array $row): string => (string) $row['bucket'], $aging);
$agingBalances = array_map(static fn(array $row): float => (float) $row['balance'], $aging);
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
 <div><h1 class="h3 mb-1">Business Intelligence</h1><p class="text-muted mb-0">Executive performance, profitability, customer experience, and operational trends.</p></div>
 <form class="d-flex flex-wrap gap-2" method="get"><input type="date" class="form-control" name="from" value="<?=e($from)?>"><input type="date" class="form-control" name="to" value="<?=e($to)?>"><button class="btn btn-primary"><i class="fa-solid fa-filter me-2"></i>Apply</button></form>
</div>
<div class="row g-3 mb-4 bi-kpi-grid">
<?php $cards=[['Invoiced',$money($summary['invoiced']??0),'fa-file-invoice-dollar','primary'],['Collected',$money($summary['collected']??0),'fa-money-check-dollar','success'],['Outstanding',$money($summary['outstanding']??0),'fa-hourglass-half','warning'],['Average ticket',$money($summary['average_ticket']??0),'fa-receipt','info'],['Estimate conversion',$percent($summary['estimate_conversion']??0),'fa-chart-line','primary'],['Repeat customer rate',$percent($summary['repeat_customer_rate']??0),'fa-rotate','success'],['Contribution',$money($summary['contribution']??0),'fa-coins',(($summary['contribution']??0)>=0?'success':'danger')],['Contribution margin',$percent($summary['contribution_margin']??0),'fa-percent',(($summary['contribution_margin']??0)>=0?'success':'danger')]]; foreach($cards as [$label,$value,$icon,$tone]):?>
 <div class="col-sm-6 col-xl-3"><div class="card h-100 bi-kpi-card"><div class="card-body d-flex justify-content-between align-items-start gap-3"><div><div class="text-muted small text-uppercase fw-semibold"><?=e($label)?></div><div class="fs-3 fw-bold mt-1"><?=e($value)?></div></div><span class="bi-kpi-icon text-bg-<?=e($tone)?>"><i class="fa-solid <?=e($icon)?>"></i></span></div></div></div>
<?php endforeach?></div>
<div class="row g-4 mb-4"><div class="col-xl-8"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Invoiced vs. collected</h2><span class="text-muted small"><?=e($from)?> to <?=e($to)?></span></div><div class="bi-chart-wrap"><canvas id="revenueTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card h-100"><div class="card-body"><h2 class="h5 mb-3">Accounts receivable aging</h2><div class="bi-chart-wrap bi-chart-wrap-small"><canvas id="agingChart"></canvas></div><div class="mt-3"><?php foreach($aging as $row):?><div class="d-flex justify-content-between py-1"><span><?=e($row['bucket'])?></span><strong><?=$money($row['balance'])?></strong></div><?php endforeach?><?php if(!$aging):?><p class="text-muted mb-0">No outstanding receivables.</p><?php endif?></div></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Revenue by service</h2><a class="btn btn-sm btn-outline-primary" href="/portal/business-intelligence/export?report=service-performance&amp;from=<?=e($from)?>&amp;to=<?=e($to)?>"><i class="fa-solid fa-download me-1"></i>CSV</a></div><div class="bi-chart-wrap"><canvas id="serviceRevenueChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card h-100"><div class="card-body"><h2 class="h5 mb-3">Customer growth signals</h2><div class="row g-3"><div class="col-6"><div class="bi-mini-stat"><span>Active recurring plans</span><strong><?=e((string)($summary['active_recurring']??0))?></strong></div></div><div class="col-6"><div class="bi-mini-stat"><span>Service requests</span><strong><?=e((string)($requests['total']??0))?></strong><small><?=$percent($requests['conversion_rate']??0)?> converted</small></div></div><div class="col-6"><div class="bi-mini-stat"><span>Referrals</span><strong><?=e((string)($referrals['total']??0))?></strong><small><?=$percent($referrals['conversion_rate']??0)?> converted</small></div></div><div class="col-6"><div class="bi-mini-stat"><span>Satisfaction</span><strong><?=number_format((float)($satisfaction['average_rating']??0),1)?> / 5</strong><small><?=e((string)($satisfaction['responses']??0))?> responses</small></div></div><div class="col-12"><div class="bi-mini-stat"><span>Net Promoter Score</span><strong><?=($satisfaction['nps']===null?'No data':e((string)$satisfaction['nps']))?></strong><small>Promoters <?=e((string)($satisfaction['promoters']??0))?> · Detractors <?=e((string)($satisfaction['detractors']??0))?></small></div></div></div></div></div></div></div>
<div class="card mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Crew profitability</h2><a class="btn btn-sm btn-outline-primary" href="/portal/business-intelligence/export?report=crew-performance&amp;from=<?=e($from)?>&amp;to=<?=e($to)?>"><i class="fa-solid fa-download me-1"></i>CSV</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Crew</th><th class="text-end">Jobs</th><th class="text-end">Revenue</th><th class="text-end">Labor hours</th><th class="text-end">Labor</th><th class="text-end">Materials</th><th class="text-end">Contribution</th></tr></thead><tbody><?php foreach($crews as $row):?><tr><td class="fw-semibold"><?=e($row['crew'])?></td><td class="text-end"><?=e((string)$row['jobs'])?></td><td class="text-end"><?=$money($row['revenue'])?></td><td class="text-end"><?=number_format((float)$row['labor_hours'],1)?></td><td class="text-end"><?=$money($row['labor_cost'])?></td><td class="text-end"><?=$money($row['material_cost'])?></td><td class="text-end fw-bold <?=((float)$row['contribution']>=0?'text-success':'text-danger')?>"><?=$money($row['contribution'])?></td></tr><?php endforeach?><?php if(!$crews):?><tr><td colspan="7" class="text-center text-muted py-4">No crew activity in this period.</td></tr><?php endif?></tbody></table></div></div></div>
<div class="row g-4"><div class="col-xl-7"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Territory and ZIP performance</h2><a class="btn btn-sm btn-outline-primary" href="/portal/business-intelligence/export?report=territory-performance&amp;from=<?=e($from)?>&amp;to=<?=e($to)?>"><i class="fa-solid fa-download me-1"></i>CSV</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>ZIP code</th><th class="text-end">Customers</th><th class="text-end">Jobs</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($territories as $row):?><tr><td><?=e($row['postal_code'])?></td><td class="text-end"><?=e((string)$row['customers'])?></td><td class="text-end"><?=e((string)$row['jobs'])?></td><td class="text-end"><?=$money($row['revenue'])?></td></tr><?php endforeach?><?php if(!$territories):?><tr><td colspan="4" class="text-center text-muted py-4">No territory activity in this period.</td></tr><?php endif?></tbody></table></div></div></div></div><div class="col-xl-5"><div class="card h-100"><div class="card-body"><h2 class="h5 mb-3">Financial composition</h2><div class="d-flex justify-content-between py-2 border-bottom"><span>Invoiced revenue</span><strong><?=$money($summary['invoiced']??0)?></strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span>Labor cost</span><strong><?=$money($summary['labor_cost']??0)?></strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span>Material cost</span><strong><?=$money($summary['material_cost']??0)?></strong></div><div class="d-flex justify-content-between py-2 fs-5"><span>Contribution</span><strong class="<?=((float)($summary['contribution']??0)>=0?'text-success':'text-danger')?>"><?=$money($summary['contribution']??0)?></strong></div><div class="alert alert-light border mt-3 mb-0 small">Contribution excludes overhead, taxes, insurance, marketing, depreciation, and other indirect expenses.</div></div></div></div></div>
<link rel="stylesheet" href="<?=asset('css/business-intelligence.css')?>?v=0.27.0"><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>const moneyTick=value=>'$'+Number(value).toLocaleString(undefined,{maximumFractionDigits:0});new Chart(document.getElementById('revenueTrendChart'),{type:'line',data:{labels:<?=json_encode($chartLabels)?>,datasets:[{label:'Invoiced',data:<?=json_encode($chartInvoiced)?>,tension:.3,fill:false},{label:'Collected',data:<?=json_encode($chartCollected)?>,tension:.3,fill:false}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},scales:{y:{beginAtZero:true,ticks:{callback:moneyTick}}}}});new Chart(document.getElementById('serviceRevenueChart'),{type:'bar',data:{labels:<?=json_encode($serviceLabels)?>,datasets:[{label:'Revenue',data:<?=json_encode($serviceRevenue)?>}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{callback:moneyTick}}}}});new Chart(document.getElementById('agingChart'),{type:'doughnut',data:{labels:<?=json_encode($agingLabels)?>,datasets:[{data:<?=json_encode($agingBalances)?>}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});</script>
