<div class="d-flex justify-content-between align-items-start mb-4">
  <div><h1 class="h3 mb-1">AI Assistant</h1><p class="text-muted mb-0">Operational analysis and reviewable drafting. Nothing is sent automatically.</p></div>
  <span class="badge text-bg-<?=($health['status']??'disabled')==='ok'?'success':(($health['status']??'')==='warning'?'warning':'secondary')?>"><?=e($health['detail']??'Disabled')?></span>
</div>
<?php if($answer):?><div class="alert alert-light border shadow-sm"><strong><?=e($lastPrompt)?></strong><hr><div style="white-space:pre-wrap"><?=e($answer)?></div></div><?php endif?>
<div class="row g-4">
 <div class="col-xl-7">
  <div class="card card-body mb-4"><h2 class="h5">Ask CastorWorks</h2><form method="post" action="/portal/ai/ask"><?=csrf_field()?><textarea name="prompt" class="form-control mb-3" rows="5" maxlength="8000" required placeholder="Summarize today's operational risks..."><?=e($lastPrompt)?></textarea><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="include_context" id="include_context" checked><label class="form-check-label" for="include_context">Include aggregate operational context</label></div><button class="btn btn-primary">Run assistant</button></form><form method="post" action="/portal/ai/daily-brief" class="d-inline ms-2"><?=csrf_field()?><button class="btn btn-outline-primary">Generate daily brief</button></form></div>
  <div class="card card-body mb-4"><h2 class="h5">Create reviewable draft</h2><form method="post" action="/portal/ai/drafts" class="row g-3"><?=csrf_field()?><div class="col-md-4"><label class="form-label">Type</label><select name="draft_type" class="form-select"><option value="estimate">Estimate narrative</option><option value="customer_reply">Customer reply</option><option value="route_recommendation">Route recommendation</option><option value="staffing_recommendation">Staffing recommendation</option></select></div><div class="col-md-8"><label class="form-label">Reference</label><input name="reference" class="form-control" placeholder="Estimate #, customer, route date, etc."></div><div class="col-12"><label class="form-label">Grounded details</label><textarea name="details" class="form-control" rows="4" required></textarea></div><div class="col-12"><label class="form-label">Additional instruction</label><input name="instruction" class="form-control"></div><div class="col-12"><button class="btn btn-primary">Create draft</button></div></form></div>
  <div class="card"><div class="card-header"><strong>Recent drafts</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Type</th><th>Reference</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($drafts as $d):?><tr><td><?=e($d['draft_type'])?></td><td><?=e($d['reference_key'])?></td><td><span class="badge text-bg-<?=$d['status']==='approved'?'success':'secondary'?>"><?=e($d['status'])?></span></td><td><?=e($d['created_at'])?></td><td><?php if($d['status']==='draft' && $d['requires_approval']):?><form method="post" action="/portal/ai/drafts/<?=$d['id']?>/approve"><?=csrf_field()?><button class="btn btn-sm btn-success">Approve</button></form><?php endif?></td></tr><?php endforeach;if(!$drafts):?><tr><td colspan="5" class="text-muted">No drafts yet.</td></tr><?php endif?></tbody></table></div></div>
 </div>
 <div class="col-xl-5">
  <?php if(in_array((string)(\App\Core\Auth::user()['role']??''),['owner','administrator'],true)):?><div class="card card-body mb-4"><h2 class="h5">Provider settings</h2><form method="post" action="/portal/ai/settings"><?=csrf_field()?><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="enabled" id="ai_enabled" <?=$settings['enabled']?'checked':''?>><label class="form-check-label" for="ai_enabled">Enable AI</label></div><label class="form-label">Provider</label><select name="provider" class="form-select mb-3"><?php foreach(['disabled','openai','azure_openai','ollama'] as $p):?><option value="<?=$p?>" <?=$settings['provider']===$p?'selected':''?>><?=e($p)?></option><?php endforeach?></select><label class="form-label">Model</label><input name="model" class="form-control mb-3" value="<?=e($settings['model'])?>"><label class="form-label">Endpoint override</label><input name="endpoint" class="form-control mb-3" value="<?=e($settings['endpoint'])?>"><div class="row"><div class="col"><label class="form-label">Daily limit</label><input type="number" min="0" name="daily_request_limit" class="form-control" value="<?=e($settings['daily_request_limit']??0)?>"></div><div class="col"><label class="form-label">Monthly limit</label><input type="number" min="0" name="monthly_request_limit" class="form-control" value="<?=e($settings['monthly_request_limit']??0)?>"></div></div><label class="form-label mt-3">Allowed roles</label><input name="allowed_roles" class="form-control mb-3" value="<?=e($settings['allowed_roles']??'owner,administrator,office,estimator')?>"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="redact_sensitive_data" id="redact" <?=($settings['redact_sensitive_data']??1)?'checked':''?>><label class="form-check-label" for="redact">Redact sensitive data</label></div><label class="form-label">System prompt</label><textarea name="system_prompt" class="form-control mb-3" rows="5"><?=e($settings['system_prompt'])?></textarea><input type="hidden" name="temperature" value="<?=e($settings['temperature'])?>"><input type="hidden" name="max_tokens" value="<?=e($settings['max_tokens'])?>"><button class="btn btn-primary">Save settings</button></form></div><?php endif?>
  <div class="card"><div class="card-header"><strong>Recent usage</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Purpose</th><th>Status</th><th>Latency</th></tr></thead><tbody><?php foreach($usage as $u):?><tr><td><?=e($u['purpose'])?></td><td><?=e($u['status'])?></td><td><?=e($u['latency_ms'])?> ms</td></tr><?php endforeach;if(!$usage):?><tr><td colspan="3" class="text-muted">No usage recorded.</td></tr><?php endif?></tbody></table></div></div>
 </div>
</div>
