<?php
$contracts=$contracts??[];$summary=$summary??[];$customers=$customers??[];$properties=$properties??[];$services=$services??[];$locations=$locations??[];
?>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
  <div><h1 class="h3 mb-1">Commercial Contracts</h1><p class="text-muted mb-0">Manage multi-location agreements, recurring service, billing, SLAs, purchase orders, renewals, and compliance.</p></div>
  <div class="d-flex gap-2">
    <form method="post" action="/portal/agreements"><?=csrf_field()?><input type="hidden" name="action" value="generate_jobs"><button class="btn btn-outline-primary"><i class="fa-solid fa-calendar-plus"></i> Generate Due Jobs</button></form>
    <form method="post" action="/portal/agreements"><?=csrf_field()?><input type="hidden" name="action" value="generate_invoices"><button class="btn btn-outline-success"><i class="fa-solid fa-file-invoice-dollar"></i> Generate Due Invoices</button></form>
  </div>
</div>
<div class="row g-3 mb-4">
<?php foreach([
 ['Active',$summary['active']??0,'success','fa-file-signature'],['Renewals due',$summary['renewals_due']??0,'warning','fa-rotate'],['SLA breaches',$summary['sla_breaches']??0,'danger','fa-triangle-exclamation'],['Compliance',$summary['compliance_attention']??0,'info','fa-shield-halved'],['Contracted value',$summary['contracted_value']??0,'primary','fa-dollar-sign']
] as $i=>$card):?>
<div class="col-6 col-lg"><div class="card h-100"><div class="card-body"><div class="text-muted small"><?=$card[0]?></div><div class="h4 mb-0"><?=$i===4?money((float)$card[1]):(int)$card[1]?></div></div></div></div>
<?php endforeach?>
</div>
<div class="row g-4">
<div class="col-xl-8">
<div class="card mb-4"><div class="card-header d-flex justify-content-between"><strong>Contract portfolio</strong><span class="badge text-bg-secondary"><?=count($contracts)?> total</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Contract</th><th>Customer</th><th>Status</th><th>Locations</th><th>Next service</th><th>Value</th><th>Actions</th></tr></thead><tbody>
<?php foreach($contracts as $c):?><tr><td><strong><?=e($c['contract_number'])?></strong><br><small><?=e($c['title'])?></small></td><td><?=e($c['display_name'])?></td><td><span class="badge text-bg-<?=($c['status']==='active'?'success':($c['status']==='renewal_pending'?'warning':'secondary'))?>"><?=e($c['status'])?></span></td><td><?=e($c['location_count'])?></td><td><?=e($c['next_service_date']??'—')?></td><td><?=money((float)($c['annual_value']??0))?></td><td><form method="post" action="/portal/agreements" class="d-flex gap-1"><?=csrf_field()?><input type="hidden" name="action" value="update_status"><input type="hidden" name="contract_id" value="<?=$c['id']?>"><select name="status" class="form-select form-select-sm"><option>draft</option><option selected>active</option><option>renewal_pending</option><option>suspended</option><option>expired</option><option>cancelled</option></select><button class="btn btn-sm btn-outline-primary">Save</button></form></td></tr><?php endforeach?>
<?php if(!$contracts):?><tr><td colspan="7" class="text-center text-muted py-4">No commercial contracts yet.</td></tr><?php endif?>
</tbody></table></div></div>
<div class="accordion" id="contractTools">
<?php
$panels=[
['newContract','Create commercial contract'],['location','Add service location'],['service','Add recurring service'],['sla','Add SLA rule'],['amendment','Add amendment'],['po','Add purchase order']
];foreach($panels as $idx=>$panel):?>
<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button <?=$idx?'collapsed':''?>" type="button" data-bs-toggle="collapse" data-bs-target="#<?=$panel[0]?>"><?=$panel[1]?></button></h2><div id="<?=$panel[0]?>" class="accordion-collapse collapse <?=$idx===0?'show':''?>" data-bs-parent="#contractTools"><div class="accordion-body">
<?php if($panel[0]==='newContract'):?>
<form method="post" action="/portal/agreements" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="create_contract">
<div class="col-md-6"><label class="form-label">Customer</label><select name="customer_id" class="form-select" required><option value="">Choose...</option><?php foreach($customers as $x):?><option value="<?=$x['id']?>"><?=e($x['display_name'])?></option><?php endforeach?></select></div>
<div class="col-md-6"><label class="form-label">Title</label><input name="title" class="form-control" required></div>
<div class="col-md-3"><label class="form-label">Start</label><input type="date" name="start_date" class="form-control" value="<?=date('Y-m-d')?>"></div><div class="col-md-3"><label class="form-label">End</label><input type="date" name="end_date" class="form-control"></div>
<div class="col-md-3"><label class="form-label">Annual value</label><input type="number" step="0.01" name="annual_value" class="form-control"></div><div class="col-md-3"><label class="form-label">Monthly value</label><input type="number" step="0.01" name="monthly_value" class="form-control"></div>
<div class="col-md-4"><label class="form-label">Billing frequency</label><select name="billing_frequency" class="form-select"><option>monthly</option><option>quarterly</option><option>semiannual</option><option>annual</option></select></div><div class="col-md-4"><label class="form-label">Billing mode</label><select name="billing_mode" class="form-select"><option value="corporate">Corporate consolidated</option><option value="location">Per location</option></select></div><div class="col-md-4"><label class="form-label">Default PO</label><input name="default_po_number" class="form-control"></div>
<div class="col-12"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="3"></textarea></div>
<div class="col-12 d-flex gap-4"><label><input type="checkbox" name="auto_renew" value="1"> Auto-renew</label><label><input type="checkbox" name="purchase_order_required" value="1"> PO required</label></div>
<div class="col-12"><button class="btn btn-primary">Create contract</button></div></form>
<?php else:?>
<form method="post" action="/portal/agreements" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="add_<?=$panel[0]?>"><div class="col-md-4"><label class="form-label">Contract</label><select name="contract_id" class="form-select" required><option value="">Choose...</option><?php foreach($contracts as $c):?><option value="<?=$c['id']?>"><?=e($c['contract_number'].' — '.$c['display_name'])?></option><?php endforeach?></select></div>
<?php if($panel[0]==='location'):?><div class="col-md-4"><label class="form-label">Property</label><select name="property_id" class="form-select" required><option value="">Choose...</option><?php foreach($properties as $p):?><option value="<?=$p['id']?>"><?=e($p['address'])?></option><?php endforeach?></select></div><div class="col-md-4"><label class="form-label">Location name</label><input name="location_name" class="form-control"></div><div class="col-md-3"><label class="form-label">Location code</label><input name="location_code" class="form-control"></div><div class="col-md-3"><label class="form-label">Site contact</label><input name="site_contact_name" class="form-control"></div><div class="col-md-3"><label class="form-label">Contact email</label><input name="site_contact_email" class="form-control"></div><div class="col-md-3"><label class="form-label">PO number</label><input name="po_number" class="form-control"></div>
<?php elseif($panel[0]==='service'):?><div class="col-md-4"><label class="form-label">Location</label><select name="contract_location_id" class="form-select"><option value="">All / corporate</option><?php foreach($locations as $l):?><option value="<?=$l['id']?>"><?=e($l['label'])?></option><?php endforeach?></select></div><div class="col-md-4"><label class="form-label">Service</label><select name="service_id" class="form-select"><option value="">Custom</option><?php foreach($services as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach?></select></div><div class="col-12"><label class="form-label">Description</label><input name="service_description" class="form-control" required></div><div class="col-md-3"><label class="form-label">Frequency</label><select name="frequency" class="form-select"><option>weekly</option><option>biweekly</option><option selected>monthly</option><option>quarterly</option><option>semiannual</option><option>annual</option><option>seasonal</option><option>custom</option></select></div><div class="col-md-3"><label class="form-label">Next date</label><input type="date" name="next_service_date" class="form-control" value="<?=date('Y-m-d')?>"></div><div class="col-md-3"><label class="form-label">Unit price</label><input type="number" step="0.01" name="unit_price" class="form-control"></div><div class="col-md-3"><label class="form-label">Duration minutes</label><input type="number" name="estimated_duration_minutes" value="120" class="form-control"></div>
<?php elseif($panel[0]==='sla'):?><div class="col-md-4"><label class="form-label">SLA name</label><input name="sla_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Event type</label><select name="event_type" class="form-select"><option>service_request</option><option>missed_service</option><option>complaint</option><option>emergency</option></select></div><div class="col-md-2"><label class="form-label">Response min.</label><input type="number" name="response_minutes" value="240" class="form-control"></div><div class="col-md-2"><label class="form-label">Resolution min.</label><input type="number" name="resolution_minutes" value="1440" class="form-control"></div>
<?php elseif($panel[0]==='amendment'):?><div class="col-md-4"><label class="form-label">Title</label><input name="amendment_title" class="form-control" required></div><div class="col-md-4"><label class="form-label">Effective date</label><input type="date" name="effective_date" value="<?=date('Y-m-d')?>" class="form-control"></div><div class="col-12"><label class="form-label">Description</label><textarea name="amendment_description" class="form-control"></textarea></div>
<?php elseif($panel[0]==='po'):?><div class="col-md-4"><label class="form-label">PO number</label><input name="po_number" class="form-control" required></div><div class="col-md-4"><label class="form-label">Amount limit</label><input type="number" step="0.01" name="amount_limit" class="form-control"></div><div class="col-md-4"><label class="form-label">Expires</label><input type="date" name="expires_at" class="form-control"></div><div class="col-12"><label class="form-label">Description</label><input name="po_description" class="form-control"></div>
<?php endif?><div class="col-12"><button class="btn btn-primary">Save</button></div></form>
<?php endif?></div></div></div><?php endforeach?></div>
</div>
<div class="col-xl-4">
<div class="card mb-4"><div class="card-header"><strong>Renewals</strong></div><div class="list-group list-group-flush"><?php foreach($renewals as $r):?><div class="list-group-item"><div class="d-flex justify-content-between"><strong><?=e($r['contract_number'])?></strong><span class="badge text-bg-warning"><?=e($r['days_remaining'])?> days</span></div><small><?=e($r['display_name'].' — '.$r['title'])?></small></div><?php endforeach?><?php if(!$renewals):?><div class="list-group-item text-muted">No renewals due.</div><?php endif?></div></div>
<div class="card"><div class="card-header"><strong>Compliance attention</strong></div><div class="list-group list-group-flush"><?php foreach($compliance as $d):?><div class="list-group-item"><strong><?=e($d['document_type'])?></strong><br><small><?=e($d['contract_number'].' — '.$d['display_name'])?></small><br><span class="text-danger"><?=e($d['expires_at']??$d['status'])?></span></div><?php endforeach?><?php if(!$compliance):?><div class="list-group-item text-muted">No compliance exceptions.</div><?php endif?></div></div>
</div></div>
