<?php
declare(strict_types=1);
use App\Core\Database;use App\Core\Env;use App\Services\EmailService;use App\Services\TemplateService;
require dirname(__DIR__).'/app/core/Env.php';Env::load(dirname(__DIR__).'/.env');spl_autoload_register(function(string $class):void{$prefix='App\\';if(!str_starts_with($class,$prefix))return;$relative=substr($class,strlen($prefix));$parts=explode('\\',$relative);$parts[0]=strtolower($parts[0]);$file=dirname(__DIR__).'/app/'.implode('/',$parts).'.php';if(is_file($file))require $file;});require dirname(__DIR__).'/app/helpers/functions.php';date_default_timezone_set((string)Env::get('APP_TIMEZONE','America/Chicago'));
$pdo=Database::connection();$mail=new EmailService();$hours=(int)Env::get('REMINDER_LOOKAHEAD_HOURS','24');
$jobs=$pdo->query("SELECT j.id,j.scheduled_start,j.service_summary,c.id customer_id,c.display_name,c.email FROM jobs j JOIN customers c ON c.id=j.customer_id LEFT JOIN notification_preferences np ON np.customer_id=c.id WHERE j.status='scheduled' AND j.scheduled_start BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL {$hours} HOUR) AND COALESCE(np.email_appointments,1)=1 AND NOT EXISTS(SELECT 1 FROM notification_logs n WHERE n.entity_type='job' AND n.entity_id=j.id AND n.template_key='appointment_reminder' AND n.status='sent')")->fetchAll();
foreach($jobs as $j){try{$subject='Reminder: Rock Bluffs service on '.date('M j, g:i A',strtotime($j['scheduled_start']));$html='<p>Hello '.e($j['display_name']).',</p><p>This is a reminder that your service is scheduled for <strong>'.e(date('l, F j \a\t g:i A',strtotime($j['scheduled_start']))).'</strong>.</p><p>'.e($j['service_summary']).'</p>';$mail->sendMail($j['email'],$subject,$html);$pdo->prepare("INSERT INTO notification_logs(customer_id,entity_type,entity_id,channel,template_key,recipient,subject,status,sent_at) VALUES(?,'job',?,'email','appointment_reminder',?,?,'sent',NOW())")->execute([$j['customer_id'],$j['id'],$j['email'],$subject]);echo "Sent job reminder {$j['id']}\n";}catch(Throwable $e){echo "Failed job {$j['id']}: {$e->getMessage()}\n";}}
$invoices=$pdo->query("SELECT i.id,i.invoice_number,i.public_token,i.balance_due,c.id customer_id,c.display_name,c.email FROM invoices i JOIN customers c ON c.id=i.customer_id LEFT JOIN notification_preferences np ON np.customer_id=c.id WHERE i.balance_due>0 AND i.due_date<CURDATE() AND i.status IN('sent','overdue') AND COALESCE(np.email_invoices,1)=1 AND NOT EXISTS(SELECT 1 FROM notification_logs n WHERE n.entity_type='invoice' AND n.entity_id=i.id AND n.template_key='invoice_overdue' AND n.status='sent' AND n.created_at>DATE_SUB(NOW(),INTERVAL 7 DAY))")->fetchAll();
foreach($invoices as $i){try{$subject='Reminder: invoice '.$i['invoice_number'].' is overdue';$url=rtrim((string)Env::get('APP_URL',''),'/').'/invoice/'.$i['public_token'];$html='<p>Hello '.e($i['display_name']).',</p><p>Your remaining balance is <strong>'.money($i['balance_due']).'</strong>.</p><p><a href="'.$url.'">View and pay invoice</a></p>';$mail->sendMail($i['email'],$subject,$html);$pdo->prepare("UPDATE invoices SET status='overdue' WHERE id=?")->execute([$i['id']]);$pdo->prepare("INSERT INTO notification_logs(customer_id,entity_type,entity_id,channel,template_key,recipient,subject,status,sent_at) VALUES(?,'invoice',?,'email','invoice_overdue',?,?,'sent',NOW())")->execute([$i['customer_id'],$i['id'],$i['email'],$subject]);echo "Sent invoice reminder {$i['id']}\n";}catch(Throwable $e){echo "Failed invoice {$i['id']}: {$e->getMessage()}\n";}}
