<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3 mb-0">New Estimate</h1><a class="btn btn-outline-secondary" href="/portal/estimates">Back</a></div>
<form method="post" action="/portal/estimates" id="estimate-form"><?=csrf_field()?><div class="row g-4"><div class="col-lg-8"><div class="card card-body"><div class="row g-3 mb-4"><div class="col-md-8"><label class="form-label">Customer</label><select required name="customer_id" class="form-select"><option value="">Choose customer...</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>" <?=((string)($_GET['customer_id']??'')===(string)$c['id'])?'selected':''?>><?=e($c['display_name'])?></option><?php endforeach?></select></div><div class="col-md-4"><label class="form-label">Valid until</label><input type="date" name="valid_until" class="form-control" value="<?=date('Y-m-d',strtotime('+30 days'))?>"></div></div><h2 class="h5">Services</h2><div class="table-responsive"><table class="table" id="items-table"><thead><tr><th>Description</th><th width="110">Qty</th><th width="140">Unit price</th><th width="120">Total</th><th width="40"></th></tr></thead><tbody></tbody></table></div><button type="button" class="btn btn-outline-primary btn-sm" id="add-item"><i class="fa-solid fa-plus"></i> Add line</button></div></div><div class="col-lg-4"><div class="card card-body sticky-lg-top" style="top:1rem"><h2 class="h5">Summary</h2><div class="d-flex justify-content-between"><span>Subtotal</span><strong id="subtotal">$0.00</strong></div><div class="mt-3"><label class="form-label">Tax rate (%)</label><input name="tax_rate" id="tax-rate" class="form-control" type="number" step="0.01" value="0"></div><hr><div class="d-flex justify-content-between fs-5"><span>Total</span><strong id="grand-total">$0.00</strong></div><div class="mt-3"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="5"></textarea></div><button class="btn btn-primary w-100 mt-3">Create Estimate</button></div></div></div></form>
<script>
const services=<?=json_encode(array_map(fn($s)=>['id'=>$s['id'],'name'=>$s['name'],'price'=>$s['default_price']??0],$services),JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT)?>;let idx=0;
function row(){const i=idx++;const opts=services.map(s=>`<option value="${s.id}" data-price="${s.price}">${s.name}</option>`).join('');return `<tr><td><select name="items[${i}][service_id]" class="form-select service-select"><option value="">Custom...</option>${opts}</select><input name="items[${i}][description]" class="form-control mt-1 description" required></td><td><input name="items[${i}][quantity]" class="form-control qty" type="number" step="0.01" value="1"></td><td><input name="items[${i}][unit_price]" class="form-control price" type="number" step="0.01" value="0"></td><td class="line-total">$0.00</td><td><button type="button" class="btn btn-sm btn-link text-danger remove">×</button></td></tr>`}
function calc(){let sub=0;document.querySelectorAll('#items-table tbody tr').forEach(tr=>{const q=parseFloat(tr.querySelector('.qty').value)||0,p=parseFloat(tr.querySelector('.price').value)||0,t=q*p;sub+=t;tr.querySelector('.line-total').textContent='$'+t.toFixed(2)});const tax=parseFloat(document.getElementById('tax-rate').value)||0;document.getElementById('subtotal').textContent='$'+sub.toFixed(2);document.getElementById('grand-total').textContent='$'+(sub*(1+tax/100)).toFixed(2)}
function add(){document.querySelector('#items-table tbody').insertAdjacentHTML('beforeend',row());calc()}add();
document.getElementById('add-item').onclick=add;document.addEventListener('input',e=>{if(e.target.matches('.qty,.price,#tax-rate'))calc()});document.addEventListener('change',e=>{if(e.target.matches('.service-select')){const o=e.target.selectedOptions[0],tr=e.target.closest('tr');tr.querySelector('.description').value=o.textContent==='Custom...'?'':o.textContent;tr.querySelector('.price').value=o.dataset.price||0;calc()}});document.addEventListener('click',e=>{if(e.target.matches('.remove')){e.target.closest('tr').remove();calc()}});
</script>
