<?php
namespace App\Controllers;
use App\Core\Auth; use App\Core\Database; use App\Core\View; use App\Services\AuditService; use App\Services\DocumentService; use App\Services\EmailService;
final class AgreementController {
 public function index():void{Auth::requireRole('owner','office');$pdo=Database::connection();$rows=$pdo->query('SELECT a.*,c.display_name FROM service_agreements a JOIN customers c ON c.id=a.customer_id ORDER BY a.created_at DESC')->fetchAll();View::render('portal/agreements/index',['title'=>'Service Agreements','rows'=>$rows,'customers'=>$pdo->query('SELECT id,display_name FROM customers ORDER BY display_name')->fetchAll()],'portal');}
 public function store():void{Auth::requireRole('owner','office');verify_csrf();$pdo=Database::connection();$num=next_number('AGR-');$token=public_token();$body=trim($_POST['body']??'');if($body===''){$body="Rock Bluffs Exterior Services agrees to perform the services described in the approved estimate or work order. Customer will provide safe access, disclose known hazards, secure pets, and pay according to stated terms. Weather and unsafe conditions may require rescheduling. Existing defects, failed seals, scratches, permanent staining, and latent glass defects are excluded unless specifically stated. Workmanship concerns must be reported within seven calendar days.";}$pdo->prepare('INSERT INTO service_agreements(agreement_number,customer_id,property_id,title,agreement_type,body,status,public_token,effective_date,expiration_date,created_by) VALUES(?,?,?,?,?,?,\'sent\',?,?,?,?,?)')->execute([$num,(int)$_POST['customer_id'],($_POST['property_id']??'')?:null,trim($_POST['title']),$_POST['agreement_type']??'residential',$body,$token,($_POST['effective_date']??'')?:null,($_POST['expiration_date']??'')?:null,Auth::id()]);AuditService::log('agreement.created','service_agreement',(int)$pdo->lastInsertId());flash('success','Agreement created and ready for signature.');redirect('/portal/agreements');}
 public function send(string $id):void{Auth::requireRole('owner','office');verify_csrf();$pdo=Database::connection();$q=$pdo->prepare('SELECT a.*,c.display_name,c.email FROM service_agreements a JOIN customers c ON c.id=a.customer_id WHERE a.id=?');$q->execute([(int)$id]);$a=$q->fetch();if(!$a||!$a['email']){flash('danger','Agreement or customer email not found.');redirect('/portal/agreements');}try{$url=rtrim((string)\App\Core\Env::get('APP_URL',''),'/').'/agreement/'.$a['public_token'];$mail=new EmailService();$message=$mail->sendMail($a['email'],'Your Rock Bluffs service agreement '.$a['agreement_number'],'<p>Hello '.htmlspecialchars($a['display_name']).',</p><p>Your service agreement is ready for review and signature.</p><p><a href="'.$url.'">Review and sign agreement</a></p>');$pdo->prepare('UPDATE service_agreements SET delivered_at=NOW(),graph_message_id=? WHERE id=?')->execute([$message['message_id']??null,$a['id']]);AuditService::log('agreement.sent','service_agreement',(int)$id);flash('success','Agreement delivered.');}catch(\Throwable $e){flash('danger',$e->getMessage());}redirect('/portal/agreements');}
 public function publicShow(string $token):void{$pdo=Database::connection();$q=$pdo->prepare('SELECT a.*,c.display_name,c.email FROM service_agreements a JOIN customers c ON c.id=a.customer_id WHERE a.public_token=?');$q->execute([$token]);$agreement=$q->fetch();if(!$agreement){http_response_code(404);exit('Agreement not found.');}if($agreement['status']==='sent')$pdo->prepare("UPDATE service_agreements SET status='viewed' WHERE id=?")->execute([$agreement['id']]);View::render('customer/agreement',['title'=>$agreement['title'],'agreement'=>$agreement,'token'=>$token],'public');}
 public function sign(string $token):void{verify_csrf();$pdo=Database::connection();$q=$pdo->prepare('SELECT id,status FROM service_agreements WHERE public_token=?');$q->execute([$token]);$a=$q->fetch();if(!$a||in_array($a['status'],['signed','cancelled','expired'],true)){http_response_code(409);exit('Agreement cannot be signed.');}$pdo->prepare("UPDATE service_agreements SET status='signed',signed_name=?,signed_email=?,signature_data=?,signed_ip=?,signed_at=NOW() WHERE id=?")->execute([trim($_POST['signed_name']),trim($_POST['signed_email']),$_POST['signature_data']??null,$_SERVER['REMOTE_ADDR']??null,$a['id']]);try{$doc=(new DocumentService())->generate('agreement',(int)$a['id']);$pdo->prepare('UPDATE service_agreements SET document_id=? WHERE id=?')->execute([$doc['id'],$a['id']]);}catch(\Throwable $e){}View::render('customer/agreement-signed',['title'=>'Agreement Signed'],'public');}
}
