<?php
namespace App\Controllers;
use App\Core\ApiAuth;use App\Core\Auth;use App\Core\Database;use App\Core\View;
final class ApiController{
 public function tokens():void{Auth::requireRole('owner','administrator');$pdo=Database::connection();View::render('portal/api/index',['title'=>'API Access','tokens'=>$pdo->query('SELECT t.*,u.name user_name FROM api_tokens t JOIN users u ON u.id=t.user_id ORDER BY t.created_at DESC')->fetchAll(),'users'=>$pdo->query("SELECT id,name FROM users WHERE status='active' ORDER BY name")->fetchAll()],'portal');}
 public function createToken():void{Auth::requireRole('owner','administrator');verify_csrf();$plain='rbes_'.bin2hex(random_bytes(24));Database::connection()->prepare('INSERT INTO api_tokens(user_id,name,token_hash,abilities_json,daily_quota,monthly_quota,expires_at) VALUES(?,?,?,?,?,?,?)')->execute([(int)$_POST['user_id'],trim($_POST['name']),hash('sha256',$plain),json_encode(array_values(array_filter(array_map('trim',explode(',',$_POST['abilities']??'*'))))),(int)($_POST['daily_quota']??600),(int)($_POST['monthly_quota']??10000),($_POST['expires_at']??'')?:null]);$_SESSION['_new_api_token']=$plain;flash('success','API token created. Copy it now; it will not be shown again.');redirect('/portal/api');}
 public function revoke(int $id):void{Auth::requireRole('owner','administrator');verify_csrf();Database::connection()->prepare('UPDATE api_tokens SET revoked_at=NOW() WHERE id=?')->execute([$id]);redirect('/portal/api');}
 public function updateQuota(int $id):void{Auth::requireRole('owner','administrator');verify_csrf();$daily=max(1,(int)($_POST['daily_quota']??600));$monthly=max($daily,(int)($_POST['monthly_quota']??10000));$warning=max(10,min(100,(int)($_POST['quota_warning_percent']??80)));Database::connection()->prepare('UPDATE api_tokens SET daily_quota=?,monthly_quota=?,quota_warning_percent=? WHERE id=?')->execute([$daily,$monthly,$warning,$id]);flash('success','API quotas updated.');redirect('/portal/api');}
 public function me():void{$u=ApiAuth::require();ApiAuth::json(['data'=>['id'=>(int)$u['user_id'],'name'=>$u['name'],'email'=>$u['email'],'role'=>$u['role']]]);}
 public function jobsToday():void{$u=ApiAuth::require();[$page,$per,$offset]=self::page();$s=Database::connection()->prepare("SELECT j.id,j.job_number,j.scheduled_start,j.status,j.service_summary,c.display_name,p.address1,p.city,p.state,p.postal_code FROM jobs j JOIN customers c ON c.id=j.customer_id LEFT JOIN properties p ON p.id=j.property_id WHERE DATE(j.scheduled_start)=CURDATE() AND (j.assigned_user_id=? OR ? IN ('owner','administrator','office')) ORDER BY j.scheduled_start LIMIT $per OFFSET $offset");$s->execute([$u['user_id'],$u['role']]);ApiAuth::json(['data'=>$s->fetchAll(),'meta'=>self::meta($page,$per)]);}
 public function customers():void{ApiAuth::require();[$page,$per,$offset]=self::page();$pdo=Database::connection();$where=[];$args=[];if(($status=trim((string)($_GET['status']??'')))!==''){$where[]='status=?';$args[]=$status;}if(($type=trim((string)($_GET['customer_type']??'')))!==''){$where[]='customer_type=?';$args[]=$type;}if(($q=trim((string)($_GET['q']??'')))!==''){$where[]='(display_name LIKE ? OR email LIKE ? OR phone LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);} $sqlWhere=$where?' WHERE '.implode(' AND ',$where):'';$count=$pdo->prepare('SELECT COUNT(*) FROM customers'.$sqlWhere);$count->execute($args);$total=(int)$count->fetchColumn();$allowed=['id','display_name','email','phone','status','customer_type','created_at','updated_at'];$requested=array_filter(array_map('trim',explode(',',(string)($_GET['fields']??''))));$fields=$requested?array_values(array_intersect($requested,$allowed)):['id','display_name','email','phone','status','customer_type','created_at','updated_at'];$sort=in_array($_GET['sort']??'display_name',$allowed,true)?$_GET['sort']:'display_name';$dir=strtolower((string)($_GET['direction']??'asc'))==='desc'?'DESC':'ASC';$stmt=$pdo->prepare('SELECT '.implode(',',$fields).' FROM customers'.$sqlWhere." ORDER BY $sort $dir LIMIT $per OFFSET $offset");$stmt->execute($args);ApiAuth::json(['data'=>$stmt->fetchAll(),'meta'=>self::meta($page,$per,$total),'links'=>['self'=>$_SERVER['REQUEST_URI']??'']]);}
 public function health():void{ApiAuth::require();ApiAuth::json(['data'=>['status'=>'ok','time'=>date(DATE_ATOM),'version'=>'18.0']]);}
 public function createCustomer():void{$u=ApiAuth::requireAbility('customers.write');$data=self::input();self::idempotent($u,$data,function()use($data){$name=trim((string)($data['display_name']??''));if($name==='')return [['error'=>'display_name is required'],422];$s=Database::connection()->prepare("INSERT INTO customers(customer_type,display_name,contact_name,email,phone,status,portal_token,portal_token_expires_at,notes) VALUES(?,?,?,?,?,'active',?,DATE_ADD(NOW(),INTERVAL 365 DAY),?)");$token=bin2hex(random_bytes(24));$s->execute([$data['customer_type']??'residential',$name,trim((string)($data['contact_name']??'')),trim((string)($data['email']??'')),trim((string)($data['phone']??'')),$token,trim((string)($data['notes']??''))]);return [['data'=>['id'=>(int)Database::connection()->lastInsertId(),'display_name'=>$name]],201];});}
 public function updateJobStatus(int $id):void{$u=ApiAuth::requireAbility('jobs.write');$data=self::input();self::idempotent($u,$data,function()use($data,$id){$pdo=Database::connection();$v=$pdo->prepare("SELECT version_no FROM api_resource_versions WHERE resource_type='job' AND resource_id=?");$v->execute([$id]);$version=(int)($v->fetchColumn()?:1);$ifMatch=trim((string)($_SERVER['HTTP_IF_MATCH']??''),' \"');if($ifMatch!==''&&$ifMatch!==(string)$version)return [['error'=>'resource version conflict','current_version'=>$version],412];$allowed=['scheduled','en_route','in_progress','completed','cancelled','on_hold'];$status=(string)($data['status']??'');if(!in_array($status,$allowed,true))return [['error'=>'invalid status'],422];$s=$pdo->prepare('UPDATE jobs SET status=? WHERE id=?');$s->execute([$status,$id]);if($s->rowCount()===0)return [['error'=>'job not found or unchanged'],404];$next=$version+1;$pdo->prepare("INSERT INTO api_resource_versions(resource_type,resource_id,version_no) VALUES('job',?,?) ON DUPLICATE KEY UPDATE version_no=VALUES(version_no)")->execute([$id,$next]);header('ETag: \"'.$next.'\"');return [['data'=>['id'=>$id,'status'=>$status,'version'=>$next]],200];});}
 public function addJobNote(int $id):void{$u=ApiAuth::requireAbility('jobs.write');$data=self::input();self::idempotent($u,$data,function()use($data,$id,$u){$body=trim((string)($data['body']??''));if($body==='')return [['error'=>'body is required'],422];$check=Database::connection()->prepare('SELECT id FROM jobs WHERE id=?');$check->execute([$id]);if(!$check->fetchColumn())return [['error'=>'job not found'],404];Database::connection()->prepare('INSERT INTO job_notes(job_id,user_id,note_type,body) VALUES(?,?,?,?)')->execute([$id,$u['user_id'],$data['note_type']??'general',$body]);return [['data'=>['id'=>(int)Database::connection()->lastInsertId(),'job_id'=>$id]],201];});}
 private static function input():array{$raw=file_get_contents('php://input');$data=json_decode($raw?:'{}',true);return is_array($data)?$data:[];}
 private static function page():array{$page=max(1,(int)($_GET['page']??1));$per=max(1,min(100,(int)($_GET['per_page']??50)));return [$page,$per,($page-1)*$per];}
 private static function meta(int $page,int $per,?int $total=null):array{$m=['page'=>$page,'per_page'=>$per];if($total!==null){$m['total']=$total;$m['total_pages']=(int)ceil($total/$per);}return $m;}
 private static function idempotent(array $u,array $data,callable $action):never{$key=trim((string)($_SERVER['HTTP_IDEMPOTENCY_KEY']??''));if($key===''){[$body,$status]=$action();ApiAuth::json($body,$status);}if(strlen($key)>190)ApiAuth::json(['error'=>'Idempotency-Key is too long'],422);$pdo=Database::connection();$path=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';$hash=hash('sha256',json_encode($data,JSON_UNESCAPED_SLASHES));$q=$pdo->prepare('SELECT request_hash,response_status,response_body FROM api_idempotency_keys WHERE api_token_id=? AND idempotency_key=? AND expires_at>NOW()');$q->execute([(int)$u['id'],$key]);if($old=$q->fetch()){if(!hash_equals($old['request_hash'],$hash))ApiAuth::json(['error'=>'idempotency key reused with different payload'],409);ApiAuth::json(json_decode($old['response_body'],true)?:[],(int)$old['response_status']);}[$body,$status]=$action();$pdo->prepare('INSERT INTO api_idempotency_keys(api_token_id,idempotency_key,request_method,request_path,request_hash,response_status,response_body,expires_at) VALUES(?,?,?,?,?,?,?,DATE_ADD(NOW(),INTERVAL 24 HOUR))')->execute([(int)$u['id'],$key,$_SERVER['REQUEST_METHOD']??'POST',$path,$hash,$status,json_encode($body,JSON_UNESCAPED_SLASHES)]);ApiAuth::json($body,$status);}
}
