<?php
namespace App\Controllers;
use App\Core\Auth; use App\Core\Database; use App\Core\View; use App\Services\AuditService;
final class BillingController {
 public function index():void{Auth::requireRole('owner','office');$pdo=Database::connection();$rows=$pdo->query('SELECT b.*,c.display_name,r.name recurring_name FROM recurring_billing_profiles b JOIN customers c ON c.id=b.customer_id LEFT JOIN recurring_services r ON r.id=b.recurring_service_id ORDER BY b.next_bill_date')->fetchAll();View::render('portal/billing/index',['title'=>'Recurring Billing','rows'=>$rows,'customers'=>$pdo->query('SELECT id,display_name FROM customers ORDER BY display_name')->fetchAll(),'recurring'=>$pdo->query('SELECT id,name FROM recurring_services WHERE active=1 ORDER BY name')->fetchAll()],'portal');}
 public function store():void{Auth::requireRole('owner','office');verify_csrf();$pdo=Database::connection();$pdo->prepare('INSERT INTO recurring_billing_profiles(customer_id,recurring_service_id,description,amount,frequency,interval_days,next_bill_date,payment_terms_days,auto_email) VALUES(?,?,?,?,?,?,?,?,?)')->execute([(int)$_POST['customer_id'],($_POST['recurring_service_id']??'')?:null,trim($_POST['description']),(float)$_POST['amount'],$_POST['frequency'],($_POST['interval_days']??'')?:null,$_POST['next_bill_date'],(int)($_POST['payment_terms_days']??15),isset($_POST['auto_email'])?1:0]);AuditService::log('recurring_billing.created','recurring_billing_profile',(int)$pdo->lastInsertId());flash('success','Recurring billing profile created.');redirect('/portal/billing');}
 public function generate():void{Auth::requireRole('owner','office');verify_csrf();$count=$this->generateDue();flash('success',$count.' recurring invoice(s) generated.');redirect('/portal/billing');}
 public function generateDue():int{$pdo=Database::connection();$rows=$pdo->query('SELECT * FROM recurring_billing_profiles WHERE active=1 AND next_bill_date<=CURDATE()')->fetchAll();$count=0;foreach($rows as $b){$num=next_number('INV-');$due=date('Y-m-d',strtotime('+'.(int)$b['payment_terms_days'].' days'));$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO invoices(invoice_number,customer_id,issue_date,due_date,status,subtotal,tax,total,balance_due,notes) VALUES(?,?,CURDATE(),?,'sent',?,0,?,?,?)")->execute([$num,$b['customer_id'],$due,$b['amount'],$b['amount'],$b['amount'],$b['description']]);$invoiceId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO invoice_items(invoice_id,description,quantity,unit_price,line_total) VALUES(?,?,?,?,?)')->execute([$invoiceId,$b['description'],1,$b['amount'],$b['amount']]);$next=match($b['frequency']){'weekly'=>'+7 days','biweekly'=>'+14 days','monthly'=>'+1 month','quarterly'=>'+3 months','semiannual'=>'+6 months','annual'=>'+1 year',default=>'+'.max(1,(int)$b['interval_days']).' days'};$pdo->prepare('UPDATE recurring_billing_profiles SET next_bill_date=? WHERE id=?')->execute([date('Y-m-d',strtotime($b['next_bill_date'].' '.$next)),$b['id']]);$pdo->commit();$count++;}catch(\Throwable $e){$pdo->rollBack();}}return $count;}
}
