<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class CertificationController{
 public function index():void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$pdo->exec("UPDATE employee_certifications SET status='expired' WHERE expires_date<CURDATE() AND status='active'");$rows=$pdo->query('SELECT c.*,u.name user_name,DATEDIFF(c.expires_date,CURDATE()) days_remaining FROM employee_certifications c JOIN users u ON u.id=c.user_id ORDER BY c.expires_date IS NULL,c.expires_date,u.name')->fetchAll();$alerts=$pdo->query("SELECT c.*,u.name user_name FROM employee_certifications c JOIN users u ON u.id=c.user_id WHERE c.status='active' AND c.expires_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 60 DAY) ORDER BY c.expires_date")->fetchAll();$renewals=$pdo->query("SELECT r.*,c.certification_name,u.name assigned_name FROM certification_renewals r JOIN employee_certifications c ON c.id=r.employee_certification_id LEFT JOIN users u ON u.id=r.assigned_to ORDER BY FIELD(r.status,'requested','in_progress','submitted','approved','rejected','cancelled'),r.target_date")->fetchAll();View::render('portal/certifications/index',['title'=>'Employee Certifications','certifications'=>$rows,'alerts'=>$alerts,'renewals'=>$renewals,'documents'=>$pdo->query('SELECT d.*,c.certification_name FROM certification_documents d JOIN employee_certifications c ON c.id=d.employee_certification_id ORDER BY d.created_at DESC')->fetchAll(),'users'=>$pdo->query("SELECT id,name FROM users WHERE status='active' ORDER BY name")->fetchAll()],'portal');}
 public function store():void{Auth::requireRole('owner','administrator','office');verify_csrf();Database::connection()->prepare('INSERT INTO employee_certifications(user_id,certification_name,issuing_organization,credential_number,issued_date,expires_date,status,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?)')->execute([(int)$_POST['user_id'],trim($_POST['certification_name']),trim($_POST['issuing_organization']??''),trim($_POST['credential_number']??''),($_POST['issued_date']??'')?:null,($_POST['expires_date']??'')?:null,$_POST['status']??'active',trim($_POST['notes']??''),Auth::id()]);AuditService::log('certification.created','employee_certification',(int)Database::connection()->lastInsertId());redirect('/portal/certifications');}
 public function status(int $id):void{Auth::requireRole('owner','administrator','office');verify_csrf();Database::connection()->prepare('UPDATE employee_certifications SET status=? WHERE id=?')->execute([$_POST['status'],$id]);redirect('/portal/certifications');}

 public function requestRenewal(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();$pdo=Database::connection();$q=$pdo->prepare('SELECT user_id,expires_date FROM employee_certifications WHERE id=?');$q->execute([$id]);$c=$q->fetch();if(!$c){http_response_code(404);exit('Certification not found');}$pdo->prepare("INSERT INTO certification_renewals(employee_certification_id,status,requested_by,assigned_to,target_date,notes) VALUES(?,'requested',?,?,?,?)")->execute([$id,Auth::id(),(int)$c['user_id'],$c['expires_date']?:null,trim($_POST['notes']??'')]);AuditService::log('certification.renewal_requested','employee_certification',$id);flash('success','Renewal workflow created.');redirect('/portal/certifications');}
 public function updateRenewal(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();$status=$_POST['status']??'in_progress';$decided=in_array($status,['approved','rejected'],true);Database::connection()->prepare("UPDATE certification_renewals SET status=?,assigned_to=?,target_date=?,notes=?,submitted_at=IF(?='submitted',NOW(),submitted_at),decided_at=?,decided_by=? WHERE id=?")->execute([$status,($_POST['assigned_to']??'')!==''?(int)$_POST['assigned_to']:null,($_POST['target_date']??'')?:null,trim($_POST['notes']??''),$status,$decided?date('Y-m-d H:i:s'):null,$decided?Auth::id():null,$id]);AuditService::log('certification.renewal_updated','certification_renewal',$id,['status'=>$status]);redirect('/portal/certifications');}

 public function uploadDocument(int $id):void{Auth::requireRole('owner','administrator','office');verify_csrf();if(empty($_FILES['document']['tmp_name'])||$_FILES['document']['error']!==UPLOAD_ERR_OK){flash('danger','Choose a document.');redirect('/portal/certifications');}$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($_FILES['document']['tmp_name']);$allowed=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'];$ext=$allowed[$mime]??'';if(!$ext||$_FILES['document']['size']>15*1024*1024){flash('danger','Use PDF, JPG, or PNG under 15 MB.');redirect('/portal/certifications');}$name=bin2hex(random_bytes(12)).'.'.$ext;$dir=upload_dir('certifications/'.$id);move_uploaded_file($_FILES['document']['tmp_name'],$dir.'/'.$name);Database::connection()->prepare('INSERT INTO certification_documents(employee_certification_id,filename,storage_path,mime_type,file_size,uploaded_by) VALUES(?,?,?,?,?,?)')->execute([$id,$_FILES['document']['name'],'certifications/'.$id.'/'.$name,$mime,(int)$_FILES['document']['size'],Auth::id()]);AuditService::log('certification.document_uploaded','employee_certification',$id);flash('success','Certification document uploaded.');redirect('/portal/certifications');}
 public function downloadDocument(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');$q=Database::connection()->prepare('SELECT * FROM certification_documents WHERE id=?');$q->execute([$id]);$d=$q->fetch();if(!$d){http_response_code(404);exit('Document not found');}$path=dirname(__DIR__,2).'/storage/uploads/'.$d['storage_path'];if(!is_file($path)){http_response_code(404);exit('File missing');}header('Content-Type: '.$d['mime_type']);header('Content-Disposition: attachment; filename="'.basename($d['filename']).'"');readfile($path);exit;}
}
