<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;use App\Services\NotificationRouteService;
final class CertificationApprovalController{
 public function index():void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$rows=$pdo->query("SELECT r.*,c.certification_name,c.expires_date,subject.name employee_name,assigned.name assigned_name,decider.name decided_name FROM certification_renewals r JOIN employee_certifications c ON c.id=r.employee_certification_id JOIN users subject ON subject.id=c.user_id LEFT JOIN users assigned ON assigned.id=r.assigned_to LEFT JOIN users decider ON decider.id=r.decided_by ORDER BY FIELD(r.status,'submitted','requested','in_progress','approved','rejected','cancelled'),r.target_date")->fetchAll();$attachments=$pdo->query('SELECT a.*,u.name uploaded_name FROM certification_approval_attachments a LEFT JOIN users u ON u.id=a.uploaded_by ORDER BY a.created_at DESC')->fetchAll();$by=[];foreach($attachments as $a)$by[$a['certification_renewal_id']][]=$a;View::render('portal/certifications/approvals',['title'=>'Certification Approval Center','renewals'=>$rows,'attachments'=>$by],'portal');}
 public function upload(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();if(empty($_FILES['document']['tmp_name'])||$_FILES['document']['error']!==UPLOAD_ERR_OK){flash('danger','Choose a document.');redirect('/portal/certification-approvals');}$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($_FILES['document']['tmp_name']);$allowed=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'];if(!isset($allowed[$mime])||$_FILES['document']['size']>15*1024*1024){flash('danger','Use PDF, JPG, or PNG under 15 MB.');redirect('/portal/certification-approvals');}$name=bin2hex(random_bytes(12)).'.'.$allowed[$mime];$dir=upload_dir('certification-approvals/'.$id);move_uploaded_file($_FILES['document']['tmp_name'],$dir.'/'.$name);Database::connection()->prepare('INSERT INTO certification_approval_attachments(certification_renewal_id,filename,storage_path,mime_type,file_size,uploaded_by) VALUES(?,?,?,?,?,?)')->execute([$id,$_FILES['document']['name'],'certification-approvals/'.$id.'/'.$name,$mime,(int)$_FILES['document']['size'],Auth::id()]);Database::connection()->prepare("UPDATE certification_renewals SET status='submitted',submitted_at=COALESCE(submitted_at,NOW()),approval_requested_at=NOW() WHERE id=?")->execute([$id]);AuditService::log('certification.approval_attachment','certification_renewal',$id);flash('success','Approval document uploaded.');redirect('/portal/certification-approvals');}
 public function decide(int $id):void{Auth::requireRole('owner','administrator','office');verify_csrf();$status=$_POST['status']??'';if(!in_array($status,['approved','rejected'],true)){flash('danger','Invalid decision.');redirect('/portal/certification-approvals');}$notes=trim($_POST['decision_notes']??'');$pdo=Database::connection();$pdo->prepare('UPDATE certification_renewals SET status=?,decision_notes=?,decided_at=NOW(),decided_by=? WHERE id=?')->execute([$status,$notes,Auth::id(),$id]);$q=$pdo->prepare('SELECT r.id,c.certification_name,u.name employee_name FROM certification_renewals r JOIN employee_certifications c ON c.id=r.employee_certification_id JOIN users u ON u.id=c.user_id WHERE r.id=?');$q->execute([$id]);$row=$q->fetch();if($row)(new NotificationRouteService())->emit('certification.'.$status,$status==='rejected'?'warning':'info','Certification '.ucfirst($status),$row['employee_name'].' - '.$row['certification_name'].($notes?': '.$notes:''),rtrim((string)\App\Core\Env::get('APP_URL',''),'/').'/portal/certification-approvals',['renewal_id'=>$id]);AuditService::log('certification.'.$status,'certification_renewal',$id,['notes'=>$notes]);flash('success','Certification renewal '.$status.'.');redirect('/portal/certification-approvals');}
 public function download(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');$q=Database::connection()->prepare('SELECT * FROM certification_approval_attachments WHERE id=?');$q->execute([$id]);$d=$q->fetch();if(!$d){http_response_code(404);exit('Document not found');}$path=dirname(__DIR__,2).'/storage/uploads/'.$d['storage_path'];if(!is_file($path)){http_response_code(404);exit('File missing');}header('Content-Type: '.$d['mime_type']);header('Content-Disposition: attachment; filename="'.basename($d['filename']).'"');readfile($path);exit;}
}
