<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class ConversationController{
 public function index():void{Auth::requireLogin();$pdo=Database::connection();$threads=$pdo->query("SELECT t.*,c.display_name customer_name,u.name assigned_name,(SELECT COUNT(*) FROM conversation_messages m WHERE m.conversation_thread_id=t.id) message_count FROM conversation_threads t JOIN customers c ON c.id=t.customer_id LEFT JOIN users u ON u.id=t.assigned_user_id ORDER BY COALESCE(t.last_message_at,t.created_at) DESC LIMIT 250")->fetchAll();$customers=$pdo->query("SELECT id,display_name FROM customers WHERE status='active' ORDER BY display_name")->fetchAll();$users=$pdo->query("SELECT id,name FROM users WHERE status='active' ORDER BY name")->fetchAll();View::render('portal/conversations/index',['title'=>'Customer Conversations','threads'=>$threads,'customers'=>$customers,'users'=>$users],'portal');}
 public function store():void{Auth::requireLogin();verify_csrf();$pdo=Database::connection();$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO conversation_threads(customer_id,job_id,subject,priority,assigned_user_id,created_by,last_message_at) VALUES(?,?,?,?,?,?,NOW())')->execute([(int)$_POST['customer_id'],($_POST['job_id']??'')!==''?(int)$_POST['job_id']:null,trim($_POST['subject']),$_POST['priority']??'normal',($_POST['assigned_user_id']??'')!==''?(int)$_POST['assigned_user_id']:null,Auth::id()]);$id=(int)$pdo->lastInsertId();if(trim($_POST['body']??'')!==''){$pdo->prepare('INSERT INTO conversation_messages(conversation_thread_id,sender_type,sender_user_id,channel,body,is_internal) VALUES(?,?,?,?,?,?)')->execute([$id,'staff',Auth::id(),$_POST['channel']??'portal',trim($_POST['body']),isset($_POST['is_internal'])?1:0]);}$pdo->commit();AuditService::log('conversation.created','conversation_thread',$id);flash('success','Conversation created.');redirect('/portal/conversations/'.$id);}catch(\Throwable $e){$pdo->rollBack();flash('danger','Unable to create conversation: '.$e->getMessage());redirect('/portal/conversations');}}
 public function show(int $id):void{Auth::requireLogin();$pdo=Database::connection();$s=$pdo->prepare('SELECT t.*,c.display_name customer_name,c.email,c.phone,u.name assigned_name FROM conversation_threads t JOIN customers c ON c.id=t.customer_id LEFT JOIN users u ON u.id=t.assigned_user_id WHERE t.id=?');$s->execute([$id]);$thread=$s->fetch();if(!$thread){http_response_code(404);exit('Conversation not found');}$m=$pdo->prepare('SELECT m.*,u.name sender_name FROM conversation_messages m LEFT JOIN users u ON u.id=m.sender_user_id WHERE m.conversation_thread_id=? ORDER BY m.created_at');$m->execute([$id]);View::render('portal/conversations/show',['title'=>$thread['subject'],'thread'=>$thread,'messages'=>$m->fetchAll()],'portal');}
 public function reply(int $id):void{Auth::requireLogin();verify_csrf();$body=trim($_POST['body']??'');if($body===''){flash('danger','Message is required.');redirect('/portal/conversations/'.$id);}Database::connection()->prepare('INSERT INTO conversation_messages(conversation_thread_id,sender_type,sender_user_id,channel,body,is_internal) VALUES(?,?,?,?,?,?)')->execute([$id,'staff',Auth::id(),$_POST['channel']??'portal',$body,isset($_POST['is_internal'])?1:0]);Database::connection()->prepare("UPDATE conversation_threads SET last_message_at=NOW(),status=? WHERE id=?")->execute([($_POST['status']??'waiting_customer'),$id]);AuditService::log('conversation.replied','conversation_thread',$id);redirect('/portal/conversations/'.$id);}
 public function close(int $id):void{Auth::requireLogin();verify_csrf();Database::connection()->prepare("UPDATE conversation_threads SET status='closed' WHERE id=?")->execute([$id]);redirect('/portal/conversations/'.$id);}
}
