<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class CorrectiveActionController{
 public function index():void{Auth::requireLogin();$pdo=Database::connection();$rows=$pdo->query("SELECT a.*,j.job_number,i.id inspection_number,u.name assigned_name FROM corrective_actions a LEFT JOIN jobs j ON j.id=a.job_id LEFT JOIN inspections i ON i.id=a.inspection_id LEFT JOIN users u ON u.id=a.assigned_user_id ORDER BY FIELD(a.status,'open','assigned','in_progress','verified','closed'),a.due_at IS NULL,a.due_at,a.created_at DESC")->fetchAll();$users=$pdo->query("SELECT id,name FROM users WHERE status='active' ORDER BY name")->fetchAll();View::render('portal/corrective-actions/index',['title'=>'Corrective Actions','actions'=>$rows,'users'=>$users],'portal');}

 public function sla():void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$summary=$pdo->query("SELECT COUNT(*) total,SUM(status NOT IN ('verified','closed') AND due_at<NOW()) overdue,SUM(status NOT IN ('verified','closed') AND due_at BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL 24 HOUR)) due_24h,SUM(status IN ('verified','closed')) completed FROM corrective_actions")->fetch();$severity=$pdo->query("SELECT severity,COUNT(*) total,SUM(status NOT IN ('verified','closed') AND due_at<NOW()) overdue FROM corrective_actions GROUP BY severity ORDER BY FIELD(severity,'critical','high','medium','low')")->fetchAll();$rows=$pdo->query("SELECT a.*,u.name assigned_name,j.job_number,TIMESTAMPDIFF(HOUR,a.due_at,NOW()) hours_overdue FROM corrective_actions a LEFT JOIN users u ON u.id=a.assigned_user_id LEFT JOIN jobs j ON j.id=a.job_id WHERE a.status NOT IN ('verified','closed') ORDER BY a.due_at IS NULL,a.due_at")->fetchAll();View::render('portal/corrective-actions/sla',['title'=>'Corrective Action SLA','summary'=>$summary,'severity'=>$severity,'actions'=>$rows],'portal');}
 public function store():void{Auth::requireLogin();verify_csrf();$pdo=Database::connection();$pdo->prepare('INSERT INTO corrective_actions(inspection_id,job_id,title,description,severity,assigned_user_id,due_at,created_by,status) VALUES(?,?,?,?,?,?,?,?,?)')->execute([($_POST['inspection_id']??'')!==''?(int)$_POST['inspection_id']:null,($_POST['job_id']??'')!==''?(int)$_POST['job_id']:null,trim($_POST['title']),trim($_POST['description']??''),$_POST['severity']??'medium',($_POST['assigned_user_id']??'')!==''?(int)$_POST['assigned_user_id']:null,($_POST['due_at']??'')?:null,Auth::id(),($_POST['assigned_user_id']??'')!==''?'assigned':'open']);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO corrective_action_events(corrective_action_id,event_type,message,actor_user_id) VALUES(?,'created',?,?)")->execute([$id,trim($_POST['description']??''),Auth::id()]);AuditService::log('corrective_action.created','corrective_action',$id);flash('success','Corrective action created.');redirect('/portal/corrective-actions');}
 public function update(int $id):void{Auth::requireLogin();verify_csrf();$status=$_POST['status']??'open';$verified=in_array($status,['verified','closed'],true);$pdo=Database::connection();$pdo->prepare('UPDATE corrective_actions SET status=?,assigned_user_id=?,due_at=?,resolution_notes=?,verified_by=?,verified_at=?,closed_at=? WHERE id=?')->execute([$status,($_POST['assigned_user_id']??'')!==''?(int)$_POST['assigned_user_id']:null,($_POST['due_at']??'')?:null,trim($_POST['resolution_notes']??''),$verified?Auth::id():null,$verified?date('Y-m-d H:i:s'):null,$status==='closed'?date('Y-m-d H:i:s'):null,$id]);$pdo->prepare('INSERT INTO corrective_action_events(corrective_action_id,event_type,message,actor_user_id,metadata_json) VALUES(?,?,?,?,?)')->execute([$id,'status_changed',trim($_POST['resolution_notes']??''),Auth::id(),json_encode(['status'=>$status])]);AuditService::log('corrective_action.updated','corrective_action',$id,['status'=>$status]);redirect('/portal/corrective-actions');}
}
