<?php
namespace App\Controllers;
use App\Core\Auth; use App\Core\Database; use App\Core\View; use App\Services\AuditService; use App\Services\CustomFieldService; use App\Services\CustomerTimelineService;
final class CustomerController
{
    public function index(): void { Auth::requireLogin(); $q=trim($_GET['q']??''); $pdo=Database::connection(); if($q!==''){ $s=$pdo->prepare("SELECT c.*, COUNT(p.id) property_count FROM customers c LEFT JOIN properties p ON p.customer_id=c.id WHERE c.display_name LIKE ? OR c.email LIKE ? OR c.phone LIKE ? GROUP BY c.id ORDER BY c.display_name"); $like="%$q%"; $s->execute([$like,$like,$like]); $customers=$s->fetchAll(); } else $customers=$pdo->query("SELECT c.*, COUNT(p.id) property_count FROM customers c LEFT JOIN properties p ON p.customer_id=c.id GROUP BY c.id ORDER BY c.created_at DESC")->fetchAll(); View::render('portal/customers/index',compact('customers','q')+['title'=>'Customers'],'portal'); }
    public function create(): void { Auth::requireLogin(); View::render('portal/customers/form',['title'=>'New Customer','customer'=>null,'properties'=>[],'customFields'=>CustomFieldService::definitions('customer'),'customValues'=>[]],'portal'); }
    public function store(): void { Auth::requireLogin(); verify_csrf(); $pdo=Database::connection(); $pdo->beginTransaction(); try { $s=$pdo->prepare('INSERT INTO customers(customer_type,display_name,contact_name,email,phone,billing_address,status,portal_token,portal_token_expires_at,notes) VALUES(?,?,?,?,?,?,?,?,DATE_ADD(NOW(),INTERVAL 365 DAY),?)'); $portalToken=bin2hex(random_bytes(24)); $s->execute([$_POST['customer_type']??'residential',trim($_POST['display_name']??''),trim($_POST['contact_name']??''),trim($_POST['email']??''),trim($_POST['phone']??''),trim($_POST['billing_address']??''),'active',$portalToken,trim($_POST['notes']??'')]); $id=(int)$pdo->lastInsertId(); if(trim($_POST['address1']??'')!==''){ $p=$pdo->prepare('INSERT INTO properties(customer_id,label,address1,address2,city,state,postal_code,gate_code,access_notes,pet_notes) VALUES(?,?,?,?,?,?,?,?,?,?)'); $p->execute([$id,$_POST['property_label']?:'Primary Property',$_POST['address1'],$_POST['address2']??'',$_POST['city']??'Plattsmouth',strtoupper($_POST['state']??'NE'),$_POST['postal_code']??'',$_POST['gate_code']??'',$_POST['access_notes']??'',$_POST['pet_notes']??'']); } CustomFieldService::save('customer',$id,$_POST,Auth::id()); $pdo->commit(); AuditService::log('customer.created','customer',$id); flash('success','Customer created.'); redirect('/portal/customers/'.$id); } catch(\Throwable $e){$pdo->rollBack(); flash('danger','Unable to create customer: '.$e->getMessage()); redirect('/portal/customers/create');} }
    public function show(string $id): void { Auth::requireLogin(); $pdo=Database::connection(); $s=$pdo->prepare('SELECT * FROM customers WHERE id=?');$s->execute([(int)$id]);$customer=$s->fetch(); if(!$customer){http_response_code(404);exit('Customer not found');} $p=$pdo->prepare('SELECT * FROM properties WHERE customer_id=?');$p->execute([(int)$id]);$properties=$p->fetchAll(); $e=$pdo->prepare('SELECT * FROM estimates WHERE customer_id=? ORDER BY created_at DESC');$e->execute([(int)$id]); $j=$pdo->prepare('SELECT * FROM jobs WHERE customer_id=? ORDER BY created_at DESC');$j->execute([(int)$id]); $i=$pdo->prepare('SELECT * FROM invoices WHERE customer_id=? ORDER BY created_at DESC');$i->execute([(int)$id]); $timeline=CustomerTimelineService::get($pdo,(int)$id); View::render('portal/customers/show',['title'=>$customer['display_name'],'customer'=>$customer,'properties'=>$properties,'estimates'=>$e->fetchAll(),'jobs'=>$j->fetchAll(),'invoices'=>$i->fetchAll(),'timeline'=>$timeline],'portal'); }
    public function edit(string $id): void { Auth::requireLogin(); $pdo=Database::connection();$s=$pdo->prepare('SELECT * FROM customers WHERE id=?');$s->execute([(int)$id]);$customer=$s->fetch();$p=$pdo->prepare('SELECT * FROM properties WHERE customer_id=? ORDER BY id LIMIT 1');$p->execute([(int)$id]);View::render('portal/customers/form',['title'=>'Edit Customer','customer'=>$customer,'properties'=>$p->fetchAll(),'customFields'=>CustomFieldService::definitions('customer'),'customValues'=>CustomFieldService::values('customer',(int)$id)],'portal'); }
    public function update(string $id): void { Auth::requireLogin(); verify_csrf(); $s=Database::connection()->prepare('UPDATE customers SET customer_type=?,display_name=?,contact_name=?,email=?,phone=?,billing_address=?,notes=? WHERE id=?');$s->execute([$_POST['customer_type'],trim($_POST['display_name']),trim($_POST['contact_name']??''),trim($_POST['email']??''),trim($_POST['phone']??''),trim($_POST['billing_address']??''),trim($_POST['notes']??''),(int)$id]); CustomFieldService::save('customer',(int)$id,$_POST,Auth::id()); AuditService::log('customer.updated','customer',(int)$id);flash('success','Customer updated.');redirect('/portal/customers/'.$id); }
}
