<?php

declare(strict_types=1);

namespace App\Controllers;

use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;use App\Services\CalendarSyncService;use App\Services\CrewOperationsService;

final class DispatchController
{
 public function index():void{Auth::requireRole('owner','office','crew_leader');$date=$_GET['date']??date('Y-m-d');$crewFilter=(int)($_GET['crew_id']??0);$db=Database::connection();$sql="SELECT j.*,c.display_name customer_name,p.address1,p.city,u.name technician_name,v.unit_number,cr.name crew_name FROM jobs j JOIN customers c ON c.id=j.customer_id LEFT JOIN properties p ON p.id=j.property_id LEFT JOIN users u ON u.id=j.assigned_user_id LEFT JOIN vehicles v ON v.id=j.assigned_vehicle_id LEFT JOIN crews cr ON cr.id=j.crew_id WHERE DATE(COALESCE(j.scheduled_start,j.route_date))=?";$args=[$date];if($crewFilter){$sql.=' AND j.crew_id=?';$args[]=$crewFilter;}$sql.=' ORDER BY COALESCE(j.crew_id,0),COALESCE(j.assigned_user_id,0),COALESCE(j.route_order,999),j.scheduled_start';$s=$db->prepare($sql);$s->execute($args);$jobs=$s->fetchAll();$techs=$db->query("SELECT id,name FROM users WHERE status='active' AND role IN ('technician','crew_leader','owner') ORDER BY name")->fetchAll();$vehicles=$db->query("SELECT id,unit_number FROM vehicles WHERE status='active' ORDER BY unit_number")->fetchAll();$crews=CrewOperationsService::crews($db);View::render('portal/dispatch/index',['title'=>'Dispatch Board','jobs'=>$jobs,'technicians'=>$techs,'vehicles'=>$vehicles,'crews'=>$crews,'date'=>$date,'crewFilter'=>$crewFilter],'portal');}
 public function assign(string $id):void{Auth::requireRole('owner','office','crew_leader');verify_csrf();$this->save((int)$id,$_POST);if(str_contains($_SERVER['HTTP_ACCEPT']??'','application/json')){header('Content-Type: application/json');echo json_encode(['ok'=>true]);return;}flash('success','Dispatch assignment saved.');redirect('/portal/dispatch?date='.urlencode($_POST['route_date']??date('Y-m-d')));}
 public function boardUpdate():void{Auth::requireRole('owner','office','crew_leader');verify_csrf();$id=(int)($_POST['job_id']??0);$this->save($id,$_POST);header('Content-Type: application/json');echo json_encode(['ok'=>true,'job_id'=>$id]);}
 private function save(int $id,array $data):void{$db=Database::connection();$crewId=($data['crew_id']??'')!==''?(int)$data['crew_id']:null;$userId=($data['assigned_user_id']??'')!==''?(int)$data['assigned_user_id']:null;$vehicleId=($data['assigned_vehicle_id']??'')!==''?(int)$data['assigned_vehicle_id']:null;if($crewId){$c=$db->prepare('SELECT crew_leader_id,default_vehicle_id FROM crews WHERE id=? AND active=1');$c->execute([$crewId]);$crew=$c->fetch();if($crew){$userId=$userId?:($crew['crew_leader_id']?:(null));$vehicleId=$vehicleId?:($crew['default_vehicle_id']?:(null));}}$old=$db->prepare('SELECT crew_id,assigned_user_id,assigned_vehicle_id FROM jobs WHERE id=?');$old->execute([$id]);$before=$old->fetch()?:[];$db->prepare('UPDATE jobs SET crew_id=?,assigned_user_id=?,assigned_vehicle_id=?,route_date=?,route_order=? WHERE id=?')->execute([$crewId,$userId,$vehicleId,$data['route_date']??date('Y-m-d'),(int)($data['route_order']??0),$id]);$db->prepare('INSERT INTO job_crew_assignment_history(job_id,crew_id,assigned_user_id,vehicle_id,assigned_by,assignment_source,notes) VALUES(?,?,?,?,?,?,?)')->execute([$id,$crewId,$userId,$vehicleId,Auth::id(),$data['assignment_source']??'dispatch',json_encode(['before'=>$before])]);AuditService::log('job.dispatched','job',$id,['crew_id'=>$crewId,'user_id'=>$userId]);CalendarSyncService::pushJob($id);}
}
