<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\Env;use App\Services\AuditService;
final class EntraController{
 public function redirect():void{$state=bin2hex(random_bytes(24));$_SESSION['entra_state']=$state;$tenant=rawurlencode((string)Env::get('M365_TENANT_ID','common'));$params=http_build_query(['client_id'=>Env::get('M365_CLIENT_ID'),'response_type'=>'code','redirect_uri'=>Env::get('M365_REDIRECT_URI'),'response_mode'=>'query','scope'=>'openid profile email User.Read','state'=>$state]);redirect('https://login.microsoftonline.com/'.$tenant.'/oauth2/v2.0/authorize?'.$params);}
 public function callback():void{if(!isset($_GET['state'])||!hash_equals($_SESSION['entra_state']??'',(string)$_GET['state'])){http_response_code(400);exit('Invalid sign-in state.');}if(empty($_GET['code'])){flash('danger','Microsoft sign-in was not completed.');redirect('/login');}$token=$this->post('https://login.microsoftonline.com/'.rawurlencode((string)Env::get('M365_TENANT_ID')).'/oauth2/v2.0/token',['client_id'=>Env::get('M365_CLIENT_ID'),'client_secret'=>Env::get('M365_CLIENT_SECRET'),'grant_type'=>'authorization_code','code'=>$_GET['code'],'redirect_uri'=>Env::get('M365_REDIRECT_URI'),'scope'=>'openid profile email User.Read']);$profile=$this->get('https://graph.microsoft.com/v1.0/me',$token['access_token']??'');$email=strtolower($profile['mail']??$profile['userPrincipalName']??'');$oid=$profile['id']??'';$pdo=Database::connection();$s=$pdo->prepare("SELECT * FROM users WHERE status='active' AND (microsoft_object_id=? OR LOWER(email)=?) LIMIT 1");$s->execute([$oid,$email]);$user=$s->fetch();if(!$user){flash('danger','Your Microsoft account has not been authorized for this portal.');redirect('/login');}$pdo->prepare('UPDATE users SET microsoft_object_id=?,entra_email=? WHERE id=?')->execute([$oid,$email,$user['id']]);Auth::login($user);AuditService::log('auth.entra_login','user',(int)$user['id']);redirect('/portal');}
 private function post(string $url,array $fields):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($fields),CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20]);$body=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);$data=json_decode((string)$body,true);if($code>=400)throw new \RuntimeException($data['error_description']??'Microsoft token request failed.');return $data;}
 private function get(string $url,string $token):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token],CURLOPT_TIMEOUT=>20]);$body=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($code>=400)throw new \RuntimeException('Unable to read Microsoft profile.');return json_decode((string)$body,true)?:[];}
}
