<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;
final class EquipmentLabelController{
 public function index():void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$items=$pdo->query("SELECT id,'inventory' asset_type,name display_name,asset_tag,qr_token FROM inventory_items WHERE asset_tag IS NOT NULL UNION ALL SELECT id,'vehicle',CONCAT(unit_number,' - ',name),asset_tag,qr_token FROM vehicles WHERE asset_tag IS NOT NULL ORDER BY display_name")->fetchAll();View::render('portal/equipment-labels/index',['title'=>'Equipment Labels','items'=>$items],'portal');}
 public function label(string $type,int $id):void{Auth::requireLogin();$pdo=Database::connection();$table=$type==='vehicle'?'vehicles':'inventory_items';$q=$pdo->prepare("SELECT id,name,asset_tag,qr_token".($type==='vehicle'?',unit_number':'')." FROM $table WHERE id=?");$q->execute([$id]);$item=$q->fetch();if(!$item){http_response_code(404);exit('Asset not found');}$item['asset_type']=$type;View::render('portal/equipment-labels/label',['title'=>'Asset Label','item'=>$item],'portal');}
 public function qr(string $type,int $id):void{Auth::requireLogin();$pdo=Database::connection();$table=$type==='vehicle'?'vehicles':'inventory_items';$q=$pdo->prepare("SELECT qr_token FROM $table WHERE id=?");$q->execute([$id]);$token=$q->fetchColumn();if(!$token){http_response_code(404);exit;} $url=app_url('/asset/scan/'.$token);header('Content-Type: image/svg+xml');if(class_exists('Endroid\QrCode\QrCode')){$qr=Endroid\QrCode\QrCode::create($url)->setSize(220)->setMargin(8);$writer=new Endroid\QrCode\Writer\SvgWriter();echo $writer->write($qr)->getString();return;}echo '<svg xmlns="http://www.w3.org/2000/svg" width="220" height="220"><rect width="100%" height="100%" fill="white"/><rect x="10" y="10" width="200" height="200" fill="none" stroke="black" stroke-width="4"/><text x="110" y="100" text-anchor="middle" font-family="sans-serif" font-size="14">QR library missing</text><text x="110" y="125" text-anchor="middle" font-family="monospace" font-size="10">'.htmlspecialchars($token).'</text></svg>';}
 public function scan(string $token):void{Auth::requireLogin();$pdo=Database::connection();foreach([['inventory_items','inventory'],['vehicles','vehicle']] as [$table,$type]){$q=$pdo->prepare("SELECT id FROM $table WHERE qr_token=?");$q->execute([$token]);if($id=$q->fetchColumn()){redirect($type==='vehicle'?'/portal/fleet':'/portal/inventory');}}http_response_code(404);exit('Asset not found');}
}
