<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;use App\Services\DocumentService;use App\Services\EmailService;use App\Services\SharePointService;use App\Services\TeamsService;
final class EstimateController
{
    public function index(): void { Auth::requireLogin();$rows=Database::connection()->query('SELECT e.*,c.display_name FROM estimates e JOIN customers c ON c.id=e.customer_id ORDER BY e.created_at DESC')->fetchAll();View::render('portal/estimates/index',['title'=>'Estimates','estimates'=>$rows],'portal'); }
    public function create(): void { Auth::requireLogin();$pdo=Database::connection();View::render('portal/estimates/form',['title'=>'New Estimate','customers'=>$pdo->query("SELECT id,display_name FROM customers WHERE status<>'inactive' ORDER BY display_name")->fetchAll(),'services'=>$pdo->query('SELECT * FROM services WHERE active=1 ORDER BY category,name')->fetchAll()],'portal'); }
    public function store(): void { Auth::requireLogin();verify_csrf();$pdo=Database::connection();$items=$_POST['items']??[];$subtotal=0;foreach($items as $item)$subtotal+=(float)($item['quantity']??0)*(float)($item['unit_price']??0);$taxRate=(float)($_POST['tax_rate']??0);$tax=round($subtotal*$taxRate/100,2);$total=$subtotal+$tax;$num=next_number('EST-');$token=public_token();$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO estimates(estimate_number,public_token,customer_id,property_id,status,subtotal,tax_amount,total,valid_until,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$num,$token,(int)$_POST['customer_id'],($_POST['property_id']??null)?:null,'draft',$subtotal,$tax,$total,$_POST['valid_until']?:null,$_POST['notes']??'',Auth::id()]);$id=(int)$pdo->lastInsertId();$is=$pdo->prepare('INSERT INTO estimate_items(estimate_id,service_id,description,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?)');foreach($items as $it){$qty=(float)($it['quantity']??0);$price=(float)($it['unit_price']??0);if($qty<=0||trim($it['description']??'')==='')continue;$is->execute([$id,$it['service_id']?:null,$it['description'],$qty,$price,$qty*$price]);}$pdo->commit();AuditService::log('estimate.created','estimate',$id,['number'=>$num]);flash('success','Estimate created.');redirect('/portal/estimates/'.$id);}catch(\Throwable $e){$pdo->rollBack();flash('danger','Estimate could not be created: '.$e->getMessage());redirect('/portal/estimates/create');}}
    public function show(string $id): void { Auth::requireLogin();$pdo=Database::connection();$s=$pdo->prepare('SELECT e.*,c.display_name,c.email,c.phone,p.address1,p.city,p.state,p.postal_code FROM estimates e JOIN customers c ON c.id=e.customer_id LEFT JOIN properties p ON p.id=e.property_id WHERE e.id=?');$s->execute([(int)$id]);$estimate=$s->fetch();if(!$estimate){http_response_code(404);exit('Estimate not found.');}$it=$pdo->prepare('SELECT * FROM estimate_items WHERE estimate_id=?');$it->execute([(int)$id]);$d=$pdo->prepare("SELECT * FROM documents WHERE reference_type='estimate' AND reference_id=? ORDER BY created_at DESC");$d->execute([(int)$id]);View::render('portal/estimates/show',['title'=>$estimate['estimate_number'],'estimate'=>$estimate,'items'=>$it->fetchAll(),'documents'=>$d->fetchAll()],'portal');}
    public function accept(string $id): void { Auth::requireLogin();verify_csrf();$pdo=Database::connection();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT * FROM estimates WHERE id=? FOR UPDATE');$s->execute([(int)$id]);$e=$s->fetch();$pdo->prepare("UPDATE estimates SET status='accepted' WHERE id=?")->execute([(int)$id]);$num=next_number('JOB-');$j=$pdo->prepare('INSERT INTO jobs(job_number,customer_id,property_id,estimate_id,service_summary,status,notes) VALUES(?,?,?,?,?,?,?)');$j->execute([$num,$e['customer_id'],$e['property_id'],$e['id'],'Services from '.$e['estimate_number'],'unscheduled',$e['notes']]);$jobId=(int)$pdo->lastInsertId();$pdo->commit();AuditService::log('estimate.accepted','estimate',(int)$id,['job_id'=>$jobId]);try{(new TeamsService())->send('Estimate accepted',$e['estimate_number'].' created job '.$num,rtrim((string)\App\Core\Env::get('APP_URL',''),'/').'/portal/jobs/'.$jobId);}catch(\Throwable){}flash('success','Estimate accepted and job created.');redirect('/portal/jobs/'.$jobId);}catch(\Throwable $x){$pdo->rollBack();flash('danger',$x->getMessage());redirect('/portal/estimates/'.$id);}}
    public function send(string $id): void { Auth::requireLogin();verify_csrf();$pdo=Database::connection();$s=$pdo->prepare('SELECT e.*,c.display_name,c.email FROM estimates e JOIN customers c ON c.id=e.customer_id WHERE e.id=?');$s->execute([(int)$id]);$e=$s->fetch();try{$doc=(new DocumentService())->generate('estimate',(int)$id);$sp=new SharePointService();if($sp->configured()){try{$remote=(string)\App\Core\Env::get('M365_SHAREPOINT_BASE_FOLDER','Exterior Services').'/Estimates/'.$doc['filename'];$up=$sp->upload($doc['path'],$remote);$pdo->prepare("UPDATE documents SET storage_status='uploaded',sharepoint_item_id=?,sharepoint_url=? WHERE id=?")->execute([$up['id']??null,$up['webUrl']??null,$doc['id']]);}catch(\Throwable $x){$pdo->prepare("UPDATE documents SET storage_status='failed',upload_error=? WHERE id=?")->execute([$x->getMessage(),$doc['id']]);}}$url=rtrim((string)\App\Core\Env::get('APP_URL',''),'/').'/estimate/'.$e['public_token'];(new EmailService())->sendMail($e['email'],'Estimate '.$e['estimate_number'].' from Rock Bluffs Exterior Services','<p>Hello '.e($e['display_name']).',</p><p>Your estimate total is <strong>'.money($e['total']).'</strong>.</p><p><a href="'.$url.'">Review and respond to estimate</a></p>',['path'=>$doc['path'],'name'=>$doc['filename'],'type'=>'application/pdf']);$pdo->prepare("UPDATE estimates SET status='sent' WHERE id=?")->execute([(int)$id]);$pdo->prepare("INSERT INTO notification_logs(customer_id,entity_type,entity_id,channel,template_key,recipient,subject,status,sent_at) VALUES(?, 'estimate', ?, 'email','estimate_sent',?,?,'sent',NOW())")->execute([$e['customer_id'],(int)$id,$e['email'],'Estimate '.$e['estimate_number']]);AuditService::log('estimate.sent','estimate',(int)$id);flash('success','Estimate PDF generated, archived, and sent through the configured email provider.');}catch(\Throwable $x){flash('danger','Estimate send failed: '.$x->getMessage());}redirect('/portal/estimates/'.$id);}
}
