<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Services\AuditService;use App\Services\SmsService;
final class FieldController{
 public function checkIn(string $id):void{Auth::requireRole('technician','crew_leader','owner');verify_csrf();$lat=$_POST['latitude']!==''?(float)$_POST['latitude']:null;$lng=$_POST['longitude']!==''?(float)$_POST['longitude']:null;$db=Database::connection();$db->prepare("UPDATE jobs SET status='in_progress',started_at=COALESCE(started_at,NOW()),check_in_at=NOW(),check_in_lat=?,check_in_lng=? WHERE id=?")->execute([$lat,$lng,(int)$id]);if($lat!==null&&$lng!==null)$db->prepare('INSERT INTO technician_locations(user_id,job_id,latitude,longitude,accuracy_meters) VALUES(?,?,?,?,?)')->execute([Auth::id(),(int)$id,$lat,$lng,$_POST['accuracy']!==''?(float)$_POST['accuracy']:null]);AuditService::log('job.check_in','job',(int)$id);flash('success','Checked in.');redirect('/portal/jobs/'.$id);}
 public function checkOut(string $id):void{Auth::requireRole('technician','crew_leader','owner');verify_csrf();Database::connection()->prepare("UPDATE jobs SET status='completed',completed_at=NOW(),check_out_at=NOW() WHERE id=?")->execute([(int)$id]);AuditService::log('job.check_out','job',(int)$id);flash('success','Job completed and checked out.');redirect('/portal/jobs/'.$id);}
 public function location(string $id):void{Auth::requireRole('technician','crew_leader','owner');verify_csrf();Database::connection()->prepare('INSERT INTO technician_locations(user_id,job_id,latitude,longitude,accuracy_meters) VALUES(?,?,?,?,?)')->execute([Auth::id(),(int)$id,(float)$_POST['latitude'],(float)$_POST['longitude'],$_POST['accuracy']!==''?(float)$_POST['accuracy']:null]);http_response_code(204);}
 public function signature(string $id):void{Auth::requireRole('technician','crew_leader','owner');verify_csrf();Database::connection()->prepare('UPDATE jobs SET customer_signature_name=?,customer_signature_data=?,customer_signed_at=NOW() WHERE id=?')->execute([trim($_POST['customer_signature_name']),$_POST['customer_signature_data']??null,(int)$id]);flash('success','Customer signature saved.');redirect('/portal/jobs/'.$id);}
 public function sms(string $id):void{Auth::requireRole('owner','office','crew_leader','technician');verify_csrf();$db=Database::connection();$s=$db->prepare('SELECT j.id,c.id customer_id,c.phone,c.display_name,p.address1,p.city FROM jobs j JOIN customers c ON c.id=j.customer_id LEFT JOIN properties p ON p.id=j.property_id WHERE j.id=?');$s->execute([(int)$id]);$j=$s->fetch();if(!$j||!$j['phone']){flash('danger','Customer has no mobile number.');redirect('/portal/jobs/'.$id);}SmsService::send((int)$j['customer_id'],(int)$id,$j['phone'],trim($_POST['body']));flash('success','SMS queued or sent.');redirect('/portal/jobs/'.$id);}
}
