<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class InspectionTemplateController{
 public function index():void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$templates=$pdo->query('SELECT t.*,(SELECT COUNT(*) FROM inspection_template_items i WHERE i.inspection_template_id=t.id) item_count FROM inspection_templates t ORDER BY t.name')->fetchAll();View::render('portal/inspection-templates/index',['title'=>'Inspection Templates','templates'=>$templates],'portal');}
 public function store():void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();Database::connection()->prepare('INSERT INTO inspection_templates(name,entity_type,description,active,created_by) VALUES(?,?,?,?,?)')->execute([trim($_POST['name']),$_POST['entity_type'],trim($_POST['description']??''),isset($_POST['active'])?1:0,Auth::id()]);$id=(int)Database::connection()->lastInsertId();AuditService::log('inspection_template.created','inspection_template',$id);redirect('/portal/inspection-templates/'.$id);}
 public function show(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$s=$pdo->prepare('SELECT * FROM inspection_templates WHERE id=?');$s->execute([$id]);$template=$s->fetch();$i=$pdo->prepare('SELECT * FROM inspection_template_items WHERE inspection_template_id=? ORDER BY sort_order,id');$i->execute([$id]);View::render('portal/inspection-templates/show',['title'=>$template['name']??'Inspection Template','template'=>$template,'items'=>$i->fetchAll()],'portal');}
 public function addItem(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();Database::connection()->prepare('INSERT INTO inspection_template_items(inspection_template_id,section_name,label,field_type,options_json,required,sort_order) VALUES(?,?,?,?,?,?,?)')->execute([$id,trim($_POST['section_name']??''),trim($_POST['label']),$_POST['field_type'],($_POST['options']??'')!==''?json_encode(array_values(array_filter(array_map('trim',explode(',',$_POST['options']))))):null,isset($_POST['required'])?1:0,(int)($_POST['sort_order']??100)]);redirect('/portal/inspection-templates/'.$id);}
 public function deleteItem(int $id):void{Auth::requireRole('owner','administrator');verify_csrf();$s=Database::connection()->prepare('SELECT inspection_template_id FROM inspection_template_items WHERE id=?');$s->execute([$id]);$tid=(int)$s->fetchColumn();Database::connection()->prepare('DELETE FROM inspection_template_items WHERE id=?')->execute([$id]);redirect('/portal/inspection-templates/'.$tid);}
}
