<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;use App\Services\NotificationRouteService;
final class NotificationRouteController{
 public function index():void{Auth::requireRole('owner','administrator');$rows=Database::connection()->query('SELECT r.*,u.name creator_name FROM notification_routes r LEFT JOIN users u ON u.id=r.created_by ORDER BY r.event_key,r.channel')->fetchAll();$logs=Database::connection()->query('SELECT * FROM notification_delivery_logs ORDER BY created_at DESC LIMIT 100')->fetchAll();View::render('portal/notifications/routes',['title'=>'Notification Routing','routes'=>$rows,'logs'=>$logs],'portal');}
 public function store():void{Auth::requireRole('owner','administrator');verify_csrf();Database::connection()->prepare('INSERT INTO notification_routes(event_key,channel,recipient_type,recipient_value,severity_min,active,created_by) VALUES(?,?,?,?,?,?,?)')->execute([trim($_POST['event_key']),$_POST['channel'],$_POST['recipient_type'],trim($_POST['recipient_value']),$_POST['severity_min']??'info',isset($_POST['active'])?1:0,Auth::id()]);AuditService::log('notification_route.created','notification_route',(int)Database::connection()->lastInsertId());flash('success','Notification route created.');redirect('/portal/notification-routes');}
 public function test():void{Auth::requireRole('owner','administrator');verify_csrf();$results=(new NotificationRouteService())->emit(trim($_POST['event_key']??'system.test'),$_POST['severity']??'info','Rock Bluffs notification test',trim($_POST['message']??'This is a notification-routing test.'),rtrim((string)\App\Core\Env::get('APP_URL',''),'/').'/portal/notification-routes',['test'=>true]);flash(count(array_filter($results,fn($r)=>$r['status']==='failed'))?'warning':'success','Notification test processed '.count($results).' deliveries.');redirect('/portal/notification-routes');}
 public function delete(int $id):void{Auth::requireRole('owner','administrator');verify_csrf();Database::connection()->prepare('DELETE FROM notification_routes WHERE id=?')->execute([$id]);redirect('/portal/notification-routes');}
}
