<?php
namespace App\Controllers;
use App\Core\Database;use App\Core\View;use App\Services\EmailService;
final class PasswordRecoveryController{
 public function requestForm():void{View::render('customer/forgot-password',['title'=>'Reset Password'],'auth');}
 public function request():void{verify_csrf();$email=strtolower(trim($_POST['email']??''));$pdo=Database::connection();$s=$pdo->prepare('SELECT ca.id,c.display_name FROM customer_accounts ca JOIN customers c ON c.id=ca.customer_id WHERE LOWER(c.email)=? AND ca.status="active" LIMIT 1');$s->execute([$email]);$a=$s->fetch();if($a){$token=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO customer_password_resets(customer_account_id,token_hash,expires_at,requested_ip) VALUES(?, ?, DATE_ADD(NOW(),INTERVAL 60 MINUTE),?)')->execute([$a['id'],hash('sha256',$token),$_SERVER['REMOTE_ADDR']??null]);$url=rtrim((string)\App\Core\Env::get('APP_URL',''),'\/').'/reset-password/'.$token;$mail=new EmailService();if($mail->configured())$mail->sendMail($email,'Reset your Rock Bluffs portal password','<p>Hello '.e($a['display_name']).',</p><p><a href="'.e($url).'">Reset your password</a>. This link expires in 60 minutes.</p>');}flash('success','If the account exists, a reset link has been sent.');redirect('/customer-login');}
 public function resetForm(string $token):void{$s=Database::connection()->prepare('SELECT id FROM customer_password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>NOW()');$s->execute([hash('sha256',$token)]);View::render('customer/reset-password',['title'=>'Choose New Password','token'=>$token,'valid'=>(bool)$s->fetchColumn()],'auth');}
 public function reset(string $token):void{verify_csrf();$p=$_POST['password']??'';if(strlen($p)<12||!preg_match('/[A-Z]/',$p)||!preg_match('/[a-z]/',$p)||!preg_match('/\d/',$p)){flash('danger','Use at least 12 characters with upper, lower, and a number.');redirect('/reset-password/'.$token);}$pdo=Database::connection();$s=$pdo->prepare('SELECT * FROM customer_password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>NOW() FOR UPDATE');$pdo->beginTransaction();$s->execute([hash('sha256',$token)]);$r=$s->fetch();if(!$r){$pdo->rollBack();flash('danger','Reset link is invalid or expired.');redirect('/customer-login');}$pdo->prepare('UPDATE customer_accounts SET password_hash=?,password_changed_at=NOW(),failed_attempts=0,locked_until=NULL WHERE id=?')->execute([password_hash($p,PASSWORD_DEFAULT),$r['customer_account_id']]);$pdo->prepare('UPDATE customer_password_resets SET used_at=NOW() WHERE id=?')->execute([$r['id']]);$pdo->commit();flash('success','Password updated.');redirect('/customer-login');}
}
