<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;use App\Services\GeocodingService;
final class PropertyController{
 public function create(string $customerId):void{Auth::requireRole('owner','office','estimator');$s=Database::connection()->prepare('SELECT * FROM customers WHERE id=?');$s->execute([(int)$customerId]);View::render('portal/properties/form',['title'=>'Add Property','customer'=>$s->fetch(),'property'=>null],'portal');}
 public function store(string $customerId):void{Auth::requireRole('owner','office','estimator');verify_csrf();$pdo=Database::connection();$s=$pdo->prepare("INSERT INTO properties(customer_id,label,address1,address2,city,state,postal_code,gate_code,access_notes,pet_notes,geocode_status) VALUES(?,?,?,?,?,?,?,?,?,?,'pending')");$s->execute([(int)$customerId,trim($_POST['label']?:'Property'),trim($_POST['address1']),trim($_POST['address2']??''),trim($_POST['city']),strtoupper(trim($_POST['state']??'NE')),trim($_POST['postal_code']),trim($_POST['gate_code']??''),trim($_POST['access_notes']??''),trim($_POST['pet_notes']??'')]);$id=(int)$pdo->lastInsertId();AuditService::log('property.created','property',$id);if(isset($_POST['geocode_now'])){try{(new GeocodingService($pdo))->geocodeProperty($id);}catch(\Throwable $e){flash('warning','Property saved, but geocoding failed: '.$e->getMessage());redirect('/portal/properties/'.$id.'/edit');}}flash('success','Property added.');redirect('/portal/customers/'.$customerId);}
 public function edit(string $id):void{Auth::requireRole('owner','office','estimator');$s=Database::connection()->prepare('SELECT p.*,c.display_name FROM properties p JOIN customers c ON c.id=p.customer_id WHERE p.id=?');$s->execute([(int)$id]);View::render('portal/properties/form',['title'=>'Edit Property','property'=>$s->fetch(),'customer'=>null],'portal');}
 public function update(string $id):void{Auth::requireRole('owner','office','estimator');verify_csrf();$pdo=Database::connection();$old=$pdo->prepare('SELECT customer_id,address1,address2,city,state,postal_code FROM properties WHERE id=?');$old->execute([(int)$id]);$before=$old->fetch();$s=$pdo->prepare('UPDATE properties SET label=?,address1=?,address2=?,city=?,state=?,postal_code=?,gate_code=?,access_notes=?,pet_notes=? WHERE id=?');$values=[trim($_POST['label']),trim($_POST['address1']),trim($_POST['address2']??''),trim($_POST['city']),strtoupper(trim($_POST['state'])),trim($_POST['postal_code']),trim($_POST['gate_code']??''),trim($_POST['access_notes']??''),trim($_POST['pet_notes']??''),(int)$id];$s->execute($values);$after=array_slice($values,1,5);$addressChanged=$before && implode('|',array_map('strval',array_slice(array_values($before),1)))!==implode('|',array_map('strval',[$values[1],$values[2],$values[3],$values[4],$values[5]]));if($addressChanged)(new GeocodingService($pdo))->markPending((int)$id);if(($_POST['latitude']??'')!==''&&($_POST['longitude']??'')!==''){try{(new GeocodingService($pdo))->setManualCoordinates((int)$id,(float)$_POST['latitude'],(float)$_POST['longitude'],isset($_POST['coordinates_verified']));}catch(\Throwable $e){flash('warning','Property saved, but coordinates were rejected: '.$e->getMessage());}}
  if(isset($_POST['geocode_now'])){try{(new GeocodingService($pdo))->geocodeProperty((int)$id,true);flash('success','Property updated and geocoded.');}catch(\Throwable $e){flash('warning','Property updated, but geocoding failed: '.$e->getMessage());}}
  AuditService::log('property.updated','property',(int)$id);redirect('/portal/customers/'.($before['customer_id']??0));}
 public function geocode(string $id):void{Auth::requireRole('owner','office','estimator');verify_csrf();try{(new GeocodingService())->geocodeProperty((int)$id,true);flash('success','Property geocoded successfully.');}catch(\Throwable $e){flash('danger','Geocoding failed: '.$e->getMessage());}redirect('/portal/properties/'.$id.'/edit');}
 public function delete(string $id):void{Auth::requireRole('owner','office');verify_csrf();$pdo=Database::connection();$q=$pdo->prepare('SELECT customer_id FROM properties WHERE id=?');$q->execute([(int)$id]);$cid=$q->fetchColumn();$pdo->prepare('DELETE FROM properties WHERE id=?')->execute([(int)$id]);AuditService::log('property.deleted','property',(int)$id);flash('success','Property removed.');redirect('/portal/customers/'.$cid);}
}
