<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class PurchaseOrderController{
 public function index():void{Auth::requireRole('owner','office');$db=Database::connection();$orders=$db->query('SELECT p.*,u.name created_name FROM purchase_orders p LEFT JOIN users u ON u.id=p.created_by ORDER BY p.created_at DESC')->fetchAll();$items=$db->query('SELECT id,name,sku,unit_cost FROM inventory_items WHERE active=1 ORDER BY name')->fetchAll();View::render('portal/purchase-orders/index',['title'=>'Purchase Orders','orders'=>$orders,'items'=>$items],'portal');}
 public function store():void{Auth::requireRole('owner','office');verify_csrf();$db=Database::connection();$db->beginTransaction();try{$po=next_number('PO-');$desc=$_POST['description']??[];$qty=$_POST['quantity']??[];$cost=$_POST['unit_cost']??[];$inv=$_POST['inventory_item_id']??[];$subtotal=0;foreach($desc as $k=>$d)$subtotal+=(float)($qty[$k]??0)*(float)($cost[$k]??0);$tax=(float)($_POST['tax']??0);$shipping=(float)($_POST['shipping']??0);$db->prepare('INSERT INTO purchase_orders(po_number,vendor_name,vendor_email,status,order_date,expected_date,subtotal,tax,shipping,total,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$po,trim($_POST['vendor_name']),trim($_POST['vendor_email']??''),'draft',($_POST['order_date']??'')?:date('Y-m-d'),($_POST['expected_date']??'')?:null,$subtotal,$tax,$shipping,$subtotal+$tax+$shipping,trim($_POST['notes']??''),Auth::id()]);$id=(int)$db->lastInsertId();$s=$db->prepare('INSERT INTO purchase_order_items(purchase_order_id,inventory_item_id,description,quantity,unit_cost,line_total) VALUES(?,?,?,?,?,?)');foreach($desc as $k=>$d){if(trim($d)==='')continue;$q=(float)($qty[$k]??0);$c=(float)($cost[$k]??0);$s->execute([$id,($inv[$k]??'')?:null,trim($d),$q,$c,$q*$c]);}$db->commit();AuditService::log('purchase_order.created','purchase_order',$id);flash('success','Purchase order created.');}catch(\Throwable $e){$db->rollBack();flash('danger','Unable to create purchase order: '.$e->getMessage());}redirect('/portal/purchase-orders');}
 public function status(string $id):void{Auth::requireRole('owner','office');verify_csrf();Database::connection()->prepare('UPDATE purchase_orders SET status=?,approved_by=IF(?="approved",?,approved_by) WHERE id=?')->execute([$_POST['status'],$_POST['status'],Auth::id(),(int)$id]);flash('success','Purchase order status updated.');redirect('/portal/purchase-orders');}
 public function receive(string $id):void{Auth::requireRole('owner','office');verify_csrf();$db=Database::connection();$db->beginTransaction();try{$s=$db->prepare('SELECT * FROM purchase_order_items WHERE purchase_order_id=?');$s->execute([(int)$id]);foreach($s->fetchAll() as $line){$receive=max(0,(float)$line['quantity']-(float)$line['quantity_received']);if($receive<=0)continue;$db->prepare('UPDATE purchase_order_items SET quantity_received=quantity_received+? WHERE id=?')->execute([$receive,$line['id']]);if($line['inventory_item_id']){$db->prepare('UPDATE inventory_items SET quantity=quantity+?,unit_cost=? WHERE id=?')->execute([$receive,$line['unit_cost'],$line['inventory_item_id']]);$db->prepare("INSERT INTO inventory_transactions(inventory_item_id,transaction_type,quantity,reference_type,reference_id,notes,created_by) VALUES(?,'receive',?,'purchase_order',?,'PO receipt',?)")->execute([$line['inventory_item_id'],$receive,(int)$id,Auth::id()]);}}$db->prepare("UPDATE purchase_orders SET status='received' WHERE id=?")->execute([(int)$id]);$db->commit();flash('success','Purchase order received into inventory.');}catch(\Throwable $e){$db->rollBack();flash('danger',$e->getMessage());}redirect('/portal/purchase-orders');}
}
