<?php
namespace App\Controllers;
use App\Core\Auth; use App\Core\Database; use App\Core\View; use App\Services\QuickBooksService; use App\Services\AuditService;
final class QuickBooksController {
 public function index():void{Auth::requireRole('owner','administrator');$pdo=Database::connection();$connection=$pdo->query("SELECT * FROM accounting_connections WHERE provider='quickbooks' LIMIT 1")->fetch();$logs=$pdo->query("SELECT * FROM accounting_sync_log WHERE provider='quickbooks' ORDER BY created_at DESC LIMIT 50")->fetchAll();View::render('portal/quickbooks/index',['title'=>'QuickBooks Online','connection'=>$connection,'logs'=>$logs,'configured'=>QuickBooksService::configured()],'portal');}
 public function connect():void{Auth::requireRole('owner','administrator');verify_csrf();if(!QuickBooksService::configured()){flash('danger','QuickBooks environment settings are incomplete.');redirect('/portal/quickbooks');}$_SESSION['qbo_state']=bin2hex(random_bytes(24));redirect(QuickBooksService::authorizationUrl($_SESSION['qbo_state']));}
 public function callback():void{Auth::requireLogin();if(!hash_equals($_SESSION['qbo_state']??'',$_GET['state']??'')){http_response_code(400);exit('Invalid QuickBooks OAuth state.');}try{$tokens=QuickBooksService::exchangeCode((string)($_GET['code']??''));$pdo=Database::connection();$pdo->prepare("UPDATE accounting_connections SET realm_id=?,access_token_enc=?,refresh_token_enc=?,token_expires_at=DATE_ADD(NOW(),INTERVAL ? SECOND),refresh_expires_at=DATE_ADD(NOW(),INTERVAL ? SECOND),status='connected',last_error=NULL WHERE provider='quickbooks'")->execute([$_GET['realmId']??null,QuickBooksService::encrypt($tokens['access_token']),QuickBooksService::encrypt($tokens['refresh_token']),$tokens['expires_in']??3600,$tokens['x_refresh_token_expires_in']??8726400]);AuditService::log('quickbooks.connected','integration');flash('success','QuickBooks Online connected.');}catch(\Throwable $e){Database::connection()->prepare("UPDATE accounting_connections SET status='error',last_error=? WHERE provider='quickbooks'")->execute([$e->getMessage()]);flash('danger',$e->getMessage());}redirect('/portal/quickbooks');}
 public function disconnect():void{Auth::requireRole('owner','administrator');verify_csrf();Database::connection()->prepare("UPDATE accounting_connections SET realm_id=NULL,access_token_enc=NULL,refresh_token_enc=NULL,status='disconnected',last_error=NULL WHERE provider='quickbooks'")->execute();AuditService::log('quickbooks.disconnected','integration');flash('success','QuickBooks disconnected.');redirect('/portal/quickbooks');}
 public function queueSync():void{Auth::requireRole('owner','office');verify_csrf();$pdo=Database::connection();$entity=$_POST['entity_type']??'invoice';$id=(int)($_POST['entity_id']??0);try{if($id<1)throw new \RuntimeException('Select a valid record.');$remote=match($entity){'customer'=>QuickBooksService::syncCustomer($id),'payment'=>QuickBooksService::syncPayment($id),default=>QuickBooksService::syncInvoice($id)};$pdo->prepare("INSERT INTO accounting_sync_log(provider,entity_type,entity_id,direction,status,message) VALUES('quickbooks',?,?, 'push','completed',?)")->execute([$entity,$id,'Remote ID '.$remote]);AuditService::log('quickbooks.synced',$entity,$id,['remote_id'=>$remote]);flash('success',ucfirst($entity).' synchronized with QuickBooks.');}catch(\Throwable $e){$pdo->prepare("INSERT INTO accounting_sync_log(provider,entity_type,entity_id,direction,status,message) VALUES('quickbooks',?,?, 'push','failed',?)")->execute([$entity,$id?:null,$e->getMessage()]);flash('danger',$e->getMessage());}redirect('/portal/quickbooks');}
}
