<?php
namespace App\Controllers;
use App\Core\Auth; use App\Core\Database; use App\Core\View; use App\Services\AuditService;
final class SelfSchedulingController {
 public function form(string $token):void{$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM customers WHERE portal_token=?');$q->execute([$token]);$customer=$q->fetch();if(!$customer){http_response_code(404);exit('Customer portal link not found.');}$p=$pdo->prepare('SELECT * FROM properties WHERE customer_id=? ORDER BY is_primary DESC,address1');$p->execute([$customer['id']]);View::render('customer/schedule',['title'=>'Request Service','customer'=>$customer,'properties'=>$p->fetchAll(),'services'=>$pdo->query('SELECT id,name FROM services WHERE active=1 ORDER BY name')->fetchAll(),'token'=>$token],'public');}
 public function submit(string $token):void{verify_csrf();$pdo=Database::connection();$q=$pdo->prepare('SELECT id FROM customers WHERE portal_token=?');$q->execute([$token]);$customerId=$q->fetchColumn();if(!$customerId){http_response_code(404);exit('Customer portal link not found.');}$public=public_token();$pdo->prepare('INSERT INTO scheduling_requests(public_token,customer_id,property_id,service_id,preferred_date,alternate_date,preferred_window,notes) VALUES(?,?,?,?,?,?,?,?)')->execute([$public,$customerId,($_POST['property_id']??'')?:null,($_POST['service_id']??'')?:null,$_POST['preferred_date'],($_POST['alternate_date']??'')?:null,$_POST['preferred_window']??'any',trim($_POST['notes']??'')]);View::render('customer/schedule-success',['title'=>'Request Received'],'public');}
 public function index():void{Auth::requireRole('owner','office','crew_leader');$pdo=Database::connection();$rows=$pdo->query("SELECT r.*,c.display_name,s.name service_name,CONCAT_WS(', ',p.address1,p.city,p.state) property_address FROM scheduling_requests r JOIN customers c ON c.id=r.customer_id LEFT JOIN services s ON s.id=r.service_id LEFT JOIN properties p ON p.id=r.property_id ORDER BY FIELD(r.status,'requested','approved','scheduled','declined','cancelled'),r.preferred_date")->fetchAll();View::render('portal/scheduling-requests/index',['title'=>'Scheduling Requests','rows'=>$rows,'users'=>$pdo->query("SELECT id,name FROM users WHERE active=1 ORDER BY name")->fetchAll()],'portal');}
 public function decide(string $id):void{Auth::requireRole('owner','office','crew_leader');verify_csrf();$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM scheduling_requests WHERE id=?');$q->execute([(int)$id]);$r=$q->fetch();if(!$r){http_response_code(404);exit;}$decision=$_POST['decision']??'declined';$jobId=null;if($decision==='scheduled'){$start=$_POST['scheduled_start']??($r['preferred_date'].' 09:00:00');$end=$_POST['scheduled_end']??date('Y-m-d H:i:s',strtotime($start.' +2 hours'));$pdo->prepare("INSERT INTO jobs(job_number,customer_id,property_id,status,scheduled_start,scheduled_end,assigned_user_id,notes) VALUES(?,?,?,'scheduled',?,?,?,?)")->execute([next_number('JOB-'),$r['customer_id'],$r['property_id'],$start,$end,($_POST['assigned_user_id']??'')?:null,$r['notes']]);$jobId=(int)$pdo->lastInsertId();}$pdo->prepare('UPDATE scheduling_requests SET status=?,job_id=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?')->execute([$decision,$jobId,Auth::id(),(int)$id]);AuditService::log('scheduling_request.'.$decision,'scheduling_request',(int)$id);flash('success','Scheduling request updated.');redirect('/portal/scheduling-requests');}
}
