<?php

declare(strict_types=1);
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class TechnicianController{
 public function today():void{Auth::requireLogin();$pdo=Database::connection();$sql="SELECT DISTINCT j.*,c.display_name,p.address1,p.city,p.state,p.postal_code,cr.name crew_name FROM jobs j JOIN customers c ON c.id=j.customer_id LEFT JOIN properties p ON p.id=j.property_id LEFT JOIN crews cr ON cr.id=j.crew_id LEFT JOIN crew_members cm ON cm.crew_id=j.crew_id AND cm.active=1 WHERE DATE(j.scheduled_start)=CURDATE()";$args=[];if(Auth::role()==='technician'){$sql.=' AND (j.assigned_user_id=? OR cm.user_id=?)';$args=[(int)Auth::id(),(int)Auth::id()];}$sql.=' ORDER BY COALESCE(cr.name,"Unassigned"),j.scheduled_start';$s=$pdo->prepare($sql);$s->execute($args);$grouped=[];foreach($s->fetchAll() as $job){$grouped[$job['crew_name']?:'Individual Assignments'][]=$job;}View::render('portal/technician/today',['title'=>"Today's Jobs",'groupedJobs'=>$grouped],'portal');}
 public function checklist(string $id):void{Auth::requireLogin();verify_csrf();$pdo=Database::connection();$ids=array_map('intval',$_POST['items']??[]);$pdo->prepare('UPDATE job_checklist_items SET completed=0,completed_by=NULL,completed_at=NULL WHERE job_id=?')->execute([(int)$id]);if($ids){$in=implode(',',array_fill(0,count($ids),'?'));$params=array_merge([Auth::id()],$ids,[(int)$id]);$pdo->prepare("UPDATE job_checklist_items SET completed=1,completed_by=?,completed_at=NOW() WHERE id IN ($in) AND job_id=?")->execute($params);}AuditService::log('job.checklist_updated','job',(int)$id);flash('success','Checklist saved.');redirect('/portal/jobs/'.$id);}
 public function seedChecklist(string $id):void{Auth::requireRole('owner','office','crew_leader');verify_csrf();$pdo=Database::connection();$count=$pdo->prepare('SELECT COUNT(*) FROM job_checklist_items WHERE job_id=?');$count->execute([(int)$id]);if((int)$count->fetchColumn()===0){$items=['Arrival and scope confirmed','Pre-existing damage documented','Work area protected','Exterior service completed','Interior service completed, if included','Screens and tracks completed, if included','Final quality inspection completed','Customer walkthrough completed','Equipment removed and gates closed'];$s=$pdo->prepare('INSERT INTO job_checklist_items(job_id,label,sort_order) VALUES(?,?,?)');foreach($items as $n=>$label)$s->execute([(int)$id,$label,$n]);}flash('success','Checklist prepared.');redirect('/portal/jobs/'.$id);}
 public function uploadPhoto(string $id):void{Auth::requireLogin();verify_csrf();if(empty($_FILES['photo']['tmp_name'])||$_FILES['photo']['error']!==UPLOAD_ERR_OK){flash('danger','Choose a valid image.');redirect('/portal/jobs/'.$id);} $mime=(new \finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);$ext=match($mime){'image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp',default=>''};if(!$ext){flash('danger','Only JPG, PNG, or WebP images are accepted.');redirect('/portal/jobs/'.$id);}if($_FILES['photo']['size']>10*1024*1024){flash('danger','Image exceeds 10 MB.');redirect('/portal/jobs/'.$id);} $name=bin2hex(random_bytes(12)).'.'.$ext;$dir=upload_dir('jobs/'.$id);$path=$dir.'/'.$name;move_uploaded_file($_FILES['photo']['tmp_name'],$path);$rel='jobs/'.$id.'/'.$name;$s=Database::connection()->prepare('INSERT INTO job_photos(job_id,photo_type,filename,storage_path,caption,uploaded_by) VALUES(?,?,?,?,?,?)');$s->execute([(int)$id,$_POST['photo_type']??'other',$_FILES['photo']['name'],$rel,trim($_POST['caption']??''),Auth::id()]);AuditService::log('job.photo_uploaded','job',(int)$id);flash('success','Photo uploaded.');redirect('/portal/jobs/'.$id);}
}
