<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;
final class TimesheetController{
 public function index():void{Auth::requireLogin();$db=Database::connection();$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-t');$where=Auth::can('owner','office','crew_leader')?'':' AND t.user_id='.(int)Auth::id();$s=$db->prepare("SELECT t.*,u.name,j.job_number,v.unit_number,TIMESTAMPDIFF(MINUTE,t.clock_in,COALESCE(t.clock_out,NOW()))-t.break_minutes minutes FROM time_entries t JOIN users u ON u.id=t.user_id LEFT JOIN jobs j ON j.id=t.job_id LEFT JOIN vehicles v ON v.id=t.vehicle_id WHERE DATE(t.clock_in) BETWEEN ? AND ? $where ORDER BY t.clock_in DESC");$s->execute([$from,$to]);$entries=$s->fetchAll();$users=$db->query("SELECT id,name FROM users WHERE status='active' ORDER BY name")->fetchAll();$jobs=$db->query("SELECT id,job_number FROM jobs WHERE status IN ('scheduled','in_progress','completed') ORDER BY created_at DESC LIMIT 200")->fetchAll();$vehicles=$db->query("SELECT id,unit_number FROM vehicles WHERE status='active' ORDER BY unit_number")->fetchAll();View::render('portal/timesheets/index',['title'=>'Timesheets','entries'=>$entries,'users'=>$users,'jobs'=>$jobs,'vehicles'=>$vehicles,'from'=>$from,'to'=>$to],'portal');}
 public function clock():void{Auth::requireLogin();verify_csrf();$db=Database::connection();$open=$db->prepare('SELECT id FROM time_entries WHERE user_id=? AND clock_out IS NULL ORDER BY clock_in DESC LIMIT 1');$open->execute([Auth::id()]);if($row=$open->fetch()){$db->prepare('UPDATE time_entries SET clock_out=NOW(),notes=CONCAT(COALESCE(notes,""),?) WHERE id=?')->execute([trim($_POST['notes']??'')?(" | ".trim($_POST['notes'])):'',$row['id']]);flash('success','Clocked out.');}else{$db->prepare('INSERT INTO time_entries(user_id,job_id,vehicle_id,clock_in,entry_type,notes,hourly_cost) VALUES(?,?,?,NOW(),?,?,?)')->execute([Auth::id(),($_POST['job_id']??'')?:null,($_POST['vehicle_id']??'')?:null,$_POST['entry_type']??'job',trim($_POST['notes']??''),($_POST['hourly_cost']??'')?:null]);flash('success','Clocked in.');}redirect('/portal/timesheets');}
 public function approve(string $id):void{Auth::requireRole('owner','office','crew_leader');verify_csrf();Database::connection()->prepare('UPDATE time_entries SET approved_by=?,approved_at=NOW() WHERE id=?')->execute([Auth::id(),(int)$id]);flash('success','Time entry approved.');redirect('/portal/timesheets');}
 public function export():void{Auth::requireRole('owner','office');$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-t');$s=Database::connection()->prepare("SELECT u.name,u.email,t.entry_type,t.clock_in,t.clock_out,t.break_minutes,ROUND((TIMESTAMPDIFF(MINUTE,t.clock_in,t.clock_out)-t.break_minutes)/60,2) hours,j.job_number,v.unit_number,t.hourly_cost FROM time_entries t JOIN users u ON u.id=t.user_id LEFT JOIN jobs j ON j.id=t.job_id LEFT JOIN vehicles v ON v.id=t.vehicle_id WHERE DATE(t.clock_in) BETWEEN ? AND ? AND t.clock_out IS NOT NULL ORDER BY u.name,t.clock_in");$s->execute([$from,$to]);header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="payroll-'.$from.'-'.$to.'.csv"');$o=fopen('php://output','w');fputcsv($o,['Employee','Email','Type','Clock In','Clock Out','Break Minutes','Hours','Job','Vehicle','Hourly Cost']);foreach($s->fetchAll() as $r)fputcsv($o,$r);fclose($o);}
}
