<?php
namespace App\Controllers;
use App\Core\Auth; use App\Core\Database; use App\Core\View; use App\Services\AuditService;
final class UserController
{
    public function index(): void {Auth::requireRole('owner','administrator');$pdo=Database::connection();$rows=$pdo->query('SELECT id,name,email,role,status,microsoft_object_id,identity_source,department,job_title,entra_manager_name,entra_manager_email,assigned_vehicle_id,service_territory_id,created_at FROM users ORDER BY name')->fetchAll();$vehicles=$pdo->query("SELECT id,unit_number,make,model FROM vehicles WHERE status<>'retired' ORDER BY unit_number")->fetchAll();$territories=[];try{$territories=$pdo->query('SELECT id,name FROM service_territories WHERE active=1 ORDER BY name')->fetchAll();}catch(\Throwable){}View::render('portal/users/index',['title'=>'Users','users'=>$rows,'vehicles'=>$vehicles,'territories'=>$territories],'portal');}
    public function store(): void {Auth::requireRole('owner','administrator');verify_csrf();$q=Database::connection()->prepare('INSERT INTO users(name,email,password_hash,role,status) VALUES(?,?,?,?,?)');$q->execute([trim($_POST['name']),strtolower(trim($_POST['email'])),password_hash((string)$_POST['password'],PASSWORD_DEFAULT),$_POST['role'],'active']);AuditService::log('user.created','user',(int)Database::connection()->lastInsertId());flash('success','User created.');redirect('/portal/users');}
    public function update(string $id): void {Auth::requireRole('owner','administrator');verify_csrf();Database::connection()->prepare('UPDATE users SET name=?,email=?,role=?,status=?,assigned_vehicle_id=?,service_territory_id=? WHERE id=?')->execute([trim($_POST['name']),strtolower(trim($_POST['email'])),$_POST['role'],$_POST['status'],($_POST['assigned_vehicle_id']??'')!==''?(int)$_POST['assigned_vehicle_id']:null,($_POST['service_territory_id']??'')!==''?(int)$_POST['service_territory_id']:null,(int)$id]);AuditService::log('user.updated','user',(int)$id);flash('success','User updated.');redirect('/portal/users');}
}
