<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Database;use App\Core\View;use App\Services\AuditService;
final class WorkOrderTemplateController{
 public function index():void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$rows=$pdo->query('SELECT w.*,s.name service_name,(SELECT COUNT(*) FROM work_order_template_tasks t WHERE t.work_order_template_id=w.id) task_count FROM work_order_templates w LEFT JOIN services s ON s.id=w.service_id ORDER BY w.name')->fetchAll();View::render('portal/work-order-templates/index',['title'=>'Work Order Templates','templates'=>$rows,'services'=>$pdo->query("SELECT id,name FROM services WHERE active=1 ORDER BY name")->fetchAll()],'portal');}
 public function store():void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();Database::connection()->prepare('INSERT INTO work_order_templates(name,service_id,default_duration_minutes,service_summary,instructions,active,created_by) VALUES(?,?,?,?,?,?,?)')->execute([trim($_POST['name']),($_POST['service_id']??'')!==''?(int)$_POST['service_id']:null,($_POST['default_duration_minutes']??'')!==''?(int)$_POST['default_duration_minutes']:null,trim($_POST['service_summary']??''),trim($_POST['instructions']??''),isset($_POST['active'])?1:0,Auth::id()]);$id=(int)Database::connection()->lastInsertId();AuditService::log('work_order_template.created','work_order_template',$id);redirect('/portal/work-order-templates/'.$id);}
 public function show(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');$pdo=Database::connection();$s=$pdo->prepare('SELECT w.*,s.name service_name FROM work_order_templates w LEFT JOIN services s ON s.id=w.service_id WHERE w.id=?');$s->execute([$id]);$template=$s->fetch();$t=$pdo->prepare('SELECT * FROM work_order_template_tasks WHERE work_order_template_id=? ORDER BY sort_order,id');$t->execute([$id]);View::render('portal/work-order-templates/show',['title'=>$template['name']??'Work Order Template','template'=>$template,'tasks'=>$t->fetchAll()],'portal');}
 public function addTask(int $id):void{Auth::requireRole('owner','administrator','office','crew_leader');verify_csrf();Database::connection()->prepare('INSERT INTO work_order_template_tasks(work_order_template_id,task_label,required,sort_order) VALUES(?,?,?,?)')->execute([$id,trim($_POST['task_label']),isset($_POST['required'])?1:0,(int)($_POST['sort_order']??100)]);redirect('/portal/work-order-templates/'.$id);}
 public function deleteTask(int $id):void{Auth::requireRole('owner','administrator');verify_csrf();$s=Database::connection()->prepare('SELECT work_order_template_id FROM work_order_template_tasks WHERE id=?');$s->execute([$id]);$tid=(int)$s->fetchColumn();Database::connection()->prepare('DELETE FROM work_order_template_tasks WHERE id=?')->execute([$id]);redirect('/portal/work-order-templates/'.$tid);}
}
