<div class="d-flex justify-content-between align-items-start mb-4"><div><a href="/portal/jobs/<?=$inspection['entity_id']?>" class="small text-decoration-none">&larr; Job <?=e($inspection['job_number'])?></a><h1 class="h3 mt-2 mb-1"><?=e($inspection['template_name'])?></h1><p class="text-muted"><?=e($inspection['display_name'])?> · <?=e($inspection['status'])?></p></div><a class="btn btn-outline-primary" href="/portal/inspections/<?=e($inspection['id'])?>/pdf"><i class="fa-solid fa-file-pdf"></i> PDF packet</a></div>
<form method="post" action="/portal/inspections/<?=$inspection['id']?>"><?=csrf_field()?>
<?php $section=null;foreach($items as $i):if($section!==$i['section_name']):if($section!==null)echo '</div></div>'; $section=$i['section_name'];?><div class="card card-body mb-3"><h2 class="h5"><?=e($section?:'Inspection')?></h2><div class="row g-3"><?php endif?>
<div class="col-12"><label class="form-label"><?=e($i['label'])?><?=$i['required']?' *':''?></label>
<?php $name='item_'.$i['id'];$v=$i['response_text']??'';if($i['field_type']==='checkbox'):?><div class="form-check"><input class="form-check-input" type="checkbox" name="<?=$name?>" value="1" <?=$v==='1'?'checked':''?>><label class="form-check-label">Pass / complete</label></div>
<?php elseif($i['field_type']==='textarea'):?><textarea class="form-control" name="<?=$name?>" rows="3" <?=$i['required']?'required':''?>><?=e($v)?></textarea>
<?php elseif($i['field_type']==='select'):?><select class="form-select" name="<?=$name?>" <?=$i['required']?'required':''?>><option value="">Choose...</option><?php foreach($i['options'] as $o):?><option value="<?=e($o)?>" <?=$v===$o?'selected':''?>><?=e($o)?></option><?php endforeach?></select>
<?php else:?><input class="form-control" type="<?=$i['field_type']==='number'?'number':'text'?>" name="<?=$name?>" value="<?=e($v)?>" <?=$i['required']?'required':''?>><?php endif?></div>
<?php endforeach;if($section!==null)echo '</div></div>';?><div class="card card-body mb-3"><label class="form-label">Inspection notes</label><textarea name="notes" class="form-control" rows="4"><?=e($inspection['notes']??'')?></textarea></div><div class="d-flex gap-2"><button class="btn btn-outline-primary">Save Draft</button><button class="btn btn-success" name="complete" value="1">Complete Inspection</button></div></form>
<div class="row g-4 mt-1"><div class="col-lg-6"><div class="portal-card"><h2 class="h5">Inspection Photos</h2><form method="post" action="/portal/inspections/<?=$inspection['id']?>/attachments" enctype="multipart/form-data" class="row g-2 mb-3"><?=csrf_field()?><div class="col-12"><input type="file" name="attachment" accept="image/jpeg,image/png,image/webp" class="form-control" required></div><div class="col-8"><input name="caption" class="form-control" placeholder="Caption"></div><div class="col-4"><button class="btn btn-primary w-100">Upload</button></div></form><div class="row g-2"><?php foreach(($attachments??[]) as $a):if($a['attachment_type']!=='photo')continue;?><div class="col-6"><div class="border rounded p-2"><img class="img-fluid rounded" src="/uploads/<?=e($a['thumbnail_path']?:$a['storage_path'])?>" alt="<?=e($a['caption']??'Inspection photo')?>"><small class="d-block mt-1"><?=e($a['caption']??$a['filename'])?></small></div></div><?php endforeach?></div></div></div><div class="col-lg-6"><div class="portal-card"><h2 class="h5">Inspection Signature</h2><canvas id="inspectionSignature" class="signature-pad"></canvas><form method="post" action="/portal/inspections/<?=$inspection['id']?>/signature" id="inspectionSignatureForm" class="mt-2"><?=csrf_field()?><input type="hidden" name="signature_data" id="inspectionSignatureData"><div class="d-flex gap-2"><button type="button" id="clearInspectionSignature" class="btn btn-outline-secondary">Clear</button><button class="btn btn-primary">Save Signature</button></div></form><?php foreach(($attachments??[]) as $a):if($a['attachment_type']!=='signature')continue;?><div class="mt-3"><img class="img-fluid border rounded" src="/uploads/<?=e($a['thumbnail_path']?:$a['storage_path'])?>" alt="Inspection signature"><small class="d-block text-muted"><?=e($a['created_at'])?></small></div><?php break;endforeach?></div></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const c=document.getElementById('inspectionSignature');if(!c)return;const x=c.getContext('2d');let drawing=false;function pos(e){const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return [p.clientX-r.left,p.clientY-r.top]}function start(e){drawing=true;x.beginPath();x.moveTo(...pos(e));e.preventDefault()}function move(e){if(!drawing)return;x.lineWidth=2;x.lineCap='round';x.strokeStyle='#06284f';x.lineTo(...pos(e));x.stroke();e.preventDefault()}function stop(){drawing=false}['mousedown','touchstart'].forEach(n=>c.addEventListener(n,start));['mousemove','touchmove'].forEach(n=>c.addEventListener(n,move));['mouseup','mouseleave','touchend'].forEach(n=>c.addEventListener(n,stop));document.getElementById('clearInspectionSignature').onclick=()=>x.clearRect(0,0,c.width,c.height);document.getElementById('inspectionSignatureForm').addEventListener('submit',()=>document.getElementById('inspectionSignatureData').value=c.toDataURL('image/png'));});</script>

<div class="mt-3"><form method="post" action="/portal/inspection-archives/<?=$inspection['id']?>"><?=csrf_field()?><button class="btn btn-outline-secondary"><i class="fa-solid fa-box-archive me-2"></i>Archive PDF packet</button></form></div>
