<section class="customer-account py-4 py-lg-5"><div class="container">
<div class="customer-hero rounded-4 p-4 p-lg-5 mb-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3 align-items-lg-center"><div><span class="eyebrow">Rock Bluffs Exterior Services</span><h1 class="brand-heading mb-2">Welcome, <?=e($customer['contact_name'] ?: $customer['display_name'])?></h1><p class="mb-0 opacity-75">Manage service requests, appointments, estimates, invoices, and messages in one place.</p></div><form method="post" action="/customer-logout"><?=csrf_field()?><button class="btn btn-light"><i class="fa-solid fa-right-from-bracket me-2"></i>Sign out</button></form></div></div>

<div class="row g-3 mb-4">
<div class="col-6 col-lg-3"><div class="account-stat"><i class="fa-solid fa-file-signature"></i><strong><?=count($estimates)?></strong><span>Estimates</span></div></div>
<div class="col-6 col-lg-3"><div class="account-stat"><i class="fa-solid fa-calendar-check"></i><strong><?=count($jobs)?></strong><span>Service visits</span></div></div>
<div class="col-6 col-lg-3"><div class="account-stat"><i class="fa-solid fa-file-invoice-dollar"></i><strong><?=count(array_filter($invoices,fn($i)=>(float)$i['balance_due']>0))?></strong><span>Open invoices</span></div></div>
<div class="col-6 col-lg-3"><div class="account-stat"><i class="fa-solid fa-arrows-rotate"></i><strong><?=count(array_filter($recurring,fn($r)=>(int)$r['active']===1))?></strong><span>Recurring plans</span></div></div>
</div>

<ul class="nav nav-pills account-nav mb-4" role="tablist">
<?php foreach([['overview','Overview','house'],['request-service','Request Service','sparkles'],['documents','Estimates & Invoices','file-lines'],['history','Service History','clock-rotate-left'],['messages','Messages','comments'],['preferences','Preferences','sliders']] as $idx=>$tab):?>
<li class="nav-item"><button class="nav-link <?=$idx===0?'active':''?>" data-bs-toggle="pill" data-bs-target="#<?=$tab[0]?>"><i class="fa-solid fa-<?=$tab[2]?> me-2"></i><?=$tab[1]?></button></li><?php endforeach?>
</ul>

<div class="tab-content">
<div class="tab-pane fade show active" id="overview"><div class="row g-4">
<div class="col-lg-7"><div class="account-card"><h2>Upcoming service</h2><?php $up=array_values(array_filter($jobs,fn($j)=>!empty($j['scheduled_start'])&&strtotime($j['scheduled_start'])>=time()&&$j['status']!=='cancelled')); if(!$up):?><p class="text-muted">No upcoming appointments. Request service whenever those windows begin judging you.</p><?php else: foreach(array_slice($up,0,5) as $j):?><div class="account-row"><div><strong><?=e($j['service_summary'])?></strong><small><?=e(date('M j, Y g:i A',strtotime($j['scheduled_start'])))?></small></div><span class="badge text-bg-primary"><?=e($j['status'])?></span></div><?php endforeach;endif?></div></div>
<div class="col-lg-5"><div class="account-card"><h2>Properties</h2><?php foreach($properties as $p):?><div class="property-chip"><i class="fa-solid fa-location-dot"></i><div><strong><?=e($p['label'])?></strong><small><?=e($p['address1'].', '.$p['city'].', '.$p['state'].' '.$p['postal_code'])?></small></div></div><?php endforeach?></div></div>
<div class="col-12"><div class="account-card"><h2>Recent requests</h2><?php if(!$requests):?><p class="text-muted mb-0">No service requests yet.</p><?php else:foreach(array_slice($requests,0,6) as $r):?><div class="account-row"><div><strong><?=e($r['subject'])?></strong><small><?=e($r['service_name']??'General service')?> · <?=e(date('M j, Y',strtotime($r['created_at'])))?></small></div><span class="badge text-bg-secondary"><?=e($r['status'])?></span></div><?php endforeach;endif?></div></div>
</div></div>

<div class="tab-pane fade" id="request-service"><div class="account-card"><h2>Request an estimate or service</h2><p class="text-muted">Tell us what needs attention and upload photos. We will review it and follow up with scheduling or an estimate.</p><form method="post" action="/account/service-requests" enctype="multipart/form-data" class="row g-3"><?=csrf_field()?><div class="col-md-6"><label class="form-label">Property</label><select name="property_id" class="form-select"><option value="">Select property</option><?php foreach($properties as $p):?><option value="<?=$p['id']?>"><?=e($p['label'].' - '.$p['address1'])?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Service</label><select name="service_id" class="form-select"><option value="">Not sure / other</option><?php foreach($services as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach?></select></div><div class="col-12"><label class="form-label">What can we help with?</label><input name="subject" class="form-control" placeholder="Window and screen cleaning, storefront service, pressure washing..." required></div><div class="col-12"><label class="form-label">Details</label><textarea name="details" rows="4" class="form-control" placeholder="Approximate window count, access concerns, preferred scope, or anything else we should know."></textarea></div><div class="col-md-4"><label class="form-label">Preferred date</label><input type="date" name="preferred_date" class="form-control"></div><div class="col-md-4"><label class="form-label">Alternate date</label><input type="date" name="alternate_date" class="form-control"></div><div class="col-md-4"><label class="form-label">Time preference</label><select name="preferred_window" class="form-select"><option value="any">Any time</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="evening">Evening</option></select></div><div class="col-12"><label class="form-label">Photos</label><input type="file" name="photos[]" class="form-control" accept="image/jpeg,image/png,image/webp" multiple><div class="form-text">Up to 10 MB per photo.</div></div><div class="col-12"><button class="btn btn-primary btn-lg"><i class="fa-solid fa-paper-plane me-2"></i>Submit Request</button></div></form></div></div>

<div class="tab-pane fade" id="documents"><div class="row g-4"><div class="col-lg-6"><div class="account-card"><h2>Estimates</h2><?php if(!$estimates):?><p class="text-muted">No estimates available.</p><?php else:foreach($estimates as $e1):?><div class="account-row"><div><strong><?=e($e1['estimate_number'])?></strong><small><?=money($e1['total'])?> · <?=e(date('M j, Y',strtotime($e1['created_at'])))?></small></div><span class="badge text-bg-light border"><?=e($e1['status'])?></span></div><?php endforeach;endif?></div></div><div class="col-lg-6"><div class="account-card"><h2>Invoices</h2><?php if(!$invoices):?><p class="text-muted">No invoices available.</p><?php else:foreach($invoices as $i):?><div class="account-row"><div><strong><?=e($i['invoice_number'])?></strong><small>Total <?=money($i['total'])?> · Balance <?=money($i['balance_due'])?></small></div><?php if(!empty($i['public_token'])):?><a class="btn btn-sm btn-outline-primary" href="/invoice/<?=e($i['public_token'])?>">View</a><?php else:?><span class="badge text-bg-light border"><?=e($i['status'])?></span><?php endif?></div><?php endforeach;endif?></div></div><div class="col-12"><div class="account-card"><h2>Agreements</h2><?php if(!$agreements):?><p class="text-muted mb-0">No agreements available.</p><?php else:foreach($agreements as $a):?><div class="account-row"><div><strong><?=e($a['title'])?></strong><small><?=e($a['agreement_number'])?> · <?=e($a['agreement_type'])?></small></div><a class="btn btn-sm btn-outline-primary" href="/agreement/<?=e($a['public_token'])?>">View</a></div><?php endforeach;endif?></div></div></div></div>

<div class="tab-pane fade" id="history"><div class="account-card"><h2>Service history</h2><?php if(!$jobs):?><p class="text-muted">No service history yet.</p><?php else:foreach($jobs as $j):?><div class="account-row"><div><strong><?=e($j['service_summary'])?></strong><small><?=e($j['job_number'])?> · <?=e($j['scheduled_start']?date('M j, Y',strtotime($j['scheduled_start'])):'Not scheduled')?></small></div><span class="badge text-bg-light border"><?=e($j['status'])?></span></div><?php endforeach;endif?></div><div class="account-card mt-4"><h2>Maintenance plans</h2><?php if(!$recurring):?><p class="text-muted mb-0">No recurring plans.</p><?php else:foreach($recurring as $r):?><div class="account-row"><div><strong><?=e($r['name'])?></strong><small><?=e($r['frequency'])?> · Next <?=e($r['next_service_date'])?></small></div><span class="badge <?=$r['active']?'text-bg-success':'text-bg-secondary'?>"><?=$r['active']?'Active':'Inactive'?></span></div><?php endforeach;endif?></div></div>

<div class="tab-pane fade" id="messages"><div class="row g-4"><div class="col-lg-7"><div class="account-card"><h2>Open conversations</h2><?php if(!$threads):?><p class="text-muted">No open conversations.</p><?php else:foreach($threads as $t):?><div class="border rounded-3 p-3 mb-3"><div class="d-flex justify-content-between"><strong><?=e($t['subject'])?></strong><span class="badge text-bg-secondary"><?=e($t['status'])?></span></div><form method="post" action="/account/conversations/<?=$t['id']?>/reply" class="mt-3"><?=csrf_field()?><textarea name="body" class="form-control mb-2" rows="2" placeholder="Reply..." required></textarea><button class="btn btn-primary btn-sm">Send Reply</button></form></div><?php endforeach;endif?></div></div><div class="col-lg-5"><div class="account-card"><h2>Start a conversation</h2><form method="post" action="/account/conversations" class="row g-3"><?=csrf_field()?><div class="col-12"><label class="form-label">Subject</label><input name="subject" class="form-control" required></div><div class="col-12"><label class="form-label">Message</label><textarea name="body" class="form-control" rows="5" required></textarea></div><div class="col-12"><button class="btn btn-primary">Send Message</button></div></form></div></div></div></div>

<div class="tab-pane fade" id="preferences"><div class="row g-4"><div class="col-lg-7"><div class="account-card"><h2>Communication preferences</h2><form method="post" action="/account/preferences"><?=csrf_field()?><h3 class="h6 mt-3">Email</h3><?php foreach(['email_estimates'=>'Estimates and proposals','email_invoices'=>'Invoices and receipts','email_appointments'=>'Appointment updates','email_marketing'=>'Seasonal offers and company news'] as $k=>$label):?><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="<?=$k?>" id="<?=$k?>" <?=($preferences[$k]??($k!=='email_marketing'))?'checked':''?>><label class="form-check-label" for="<?=$k?>"><?=$label?></label></div><?php endforeach?><h3 class="h6 mt-4">Text messages</h3><?php foreach(['sms_appointments'=>'Appointment updates','sms_invoices'=>'Invoice reminders','sms_marketing'=>'Seasonal offers'] as $k=>$label):?><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="<?=$k?>" id="<?=$k?>" <?=($preferences[$k]??false)?'checked':''?>><label class="form-check-label" for="<?=$k?>"><?=$label?></label></div><?php endforeach?><button class="btn btn-primary mt-3">Save Preferences</button></form></div></div><div class="col-lg-5"><div class="account-card" id="referrals"><h2>Refer someone</h2><form method="post" action="/account/referrals" class="row g-3"><?=csrf_field()?><div class="col-12"><input name="name" class="form-control" placeholder="Name" required></div><div class="col-12"><input name="email" type="email" class="form-control" placeholder="Email"></div><div class="col-12"><input name="phone" class="form-control" placeholder="Phone"></div><div class="col-12"><textarea name="notes" class="form-control" rows="2" placeholder="Notes"></textarea></div><div class="col-12"><button class="btn btn-outline-primary">Submit Referral</button></div></form></div><div class="account-card mt-4" id="feedback"><h2>Share feedback</h2><form method="post" action="/account/surveys" class="row g-3"><?=csrf_field()?><div class="col-12"><label class="form-label">Overall rating</label><select name="rating" class="form-select" required><option value="">Choose</option><option value="5">5 - Excellent</option><option value="4">4 - Very good</option><option value="3">3 - Good</option><option value="2">2 - Needs improvement</option><option value="1">1 - Poor</option></select></div><div class="col-12"><textarea name="comments" class="form-control" rows="3" placeholder="Comments"></textarea></div><div class="col-12"><button class="btn btn-outline-primary">Send Feedback</button></div></form></div></div></div></div>
</div></div></section>
