<div class="container py-5" style="max-width:900px">
<div class="card shadow-sm"><div class="card-body p-4 p-lg-5">
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 mb-1"><?=e($agreement['title'])?></h1><div class="text-muted"><?=e($agreement['agreement_number'])?> · <?=e($agreement['display_name'])?></div></div><span class="badge text-bg-<?=($agreement['status']==='signed'?'success':'primary')?>"><?=e($agreement['status'])?></span></div>
<div class="border rounded p-4 bg-light mb-4" style="white-space:pre-wrap"><?=e($agreement['body'])?></div>
<div class="row g-3 mb-4"><div class="col-md-6"><strong>Effective</strong><br><?=e($agreement['effective_date']??'Upon signature')?></div><div class="col-md-6"><strong>Expiration</strong><br><?=e($agreement['expiration_date']??'As stated in contract')?></div></div>
<?php if(!in_array($agreement['status'],['signed','cancelled','expired'],true)):?>
<form method="post" action="/agreement/<?=e($token)?>/sign" class="row g-3"><?=csrf_field()?><div class="col-md-6"><label class="form-label">Authorized signer</label><input name="signed_name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" name="signed_email" class="form-control" required value="<?=e($agreement['email']??'')?>"></div><div class="col-12"><label class="form-label">Signature</label><input name="signature_data" class="form-control" placeholder="Type full legal name" required></div><div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" required> <span class="form-check-label">I am authorized to sign and agree to the terms above.</span></label></div><div class="col-12"><button class="btn btn-primary btn-lg">Sign agreement</button></div></form>
<?php else:?><div class="alert alert-success mb-0">This agreement has been signed.</div><?php endif?>
</div></div></div>
