<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 mb-1">GPS Tracking</h1><p class="text-muted mb-0">Control field location collection, retention, arrival detection, and stale-location thresholds.</p></div><span class="badge text-bg-<?= !empty($policy['enabled']) ? 'success' : 'secondary' ?>"><?= !empty($policy['enabled']) ? 'Enabled' : 'Disabled' ?></span></div>
<div class="row g-4"><div class="col-xl-5"><div class="card"><div class="card-body"><form method="post" action="/portal/gps-policies"><?= csrf_field() ?>
<div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="enabled" id="gpsEnabled" <?= checked(!empty($policy['enabled'])) ?>><label class="form-check-label" for="gpsEnabled">Enable technician GPS tracking</label></div>
<div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="clocked_in_only" id="clockedOnly" <?= checked(!isset($policy['clocked_in_only']) || !empty($policy['clocked_in_only'])) ?>><label class="form-check-label" for="clockedOnly">Collect only while clocked in</label></div>
<div class="mb-3"><label class="form-label">Update interval</label><div class="input-group"><input class="form-control" type="number" min="15" max="900" name="update_interval_seconds" value="<?= e($policy['update_interval_seconds'] ?? 60) ?>"><span class="input-group-text">seconds</span></div></div>
<div class="mb-3"><label class="form-label">Arrival radius</label><div class="input-group"><input class="form-control" type="number" min="25" max="1000" name="arrival_radius_meters" value="<?= e($policy['arrival_radius_meters'] ?? 125) ?>"><span class="input-group-text">meters</span></div></div>
<div class="mb-3"><label class="form-label">Stale-location warning</label><div class="input-group"><input class="form-control" type="number" min="2" max="120" name="stale_after_minutes" value="<?= e($policy['stale_after_minutes'] ?? 10) ?>"><span class="input-group-text">minutes</span></div></div>
<div class="mb-3"><label class="form-label">History retention</label><div class="input-group"><input class="form-control" type="number" min="1" max="3650" name="retention_days" value="<?= e($policy['retention_days'] ?? 90) ?>"><span class="input-group-text">days</span></div></div>
<button class="btn btn-primary">Save GPS policy</button></form></div></div></div>
<div class="col-xl-7"><div class="card"><div class="card-body"><h2 class="h5">Recent field locations</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Technician</th><th>Assignment</th><th>Accuracy</th><th>Captured</th></tr></thead><tbody><?php foreach($recent as $r): ?><tr><td><?= e($r['user_name'] ?? 'Unknown') ?></td><td><?= e($r['job_number'] ?: ($r['crew_name'] ?: ($r['unit_number'] ?: 'Unassigned'))) ?></td><td><?= $r['accuracy_meters'] !== null ? e(round((float)$r['accuracy_meters']).' m') : '—' ?></td><td><?= e($r['captured_at']) ?></td></tr><?php endforeach; if(!$recent): ?><tr><td colspan="4" class="text-muted">No location updates recorded.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
