<?php
namespace App\Core;
final class ApiAuth {
 public static function user():?array{
  $header=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/^Bearer\s+(.+)$/i',$header,$m))return null;$hash=hash('sha256',$m[1]);
  $s=Database::connection()->prepare("SELECT t.*,u.name,u.email,u.role,u.status user_status FROM api_tokens t JOIN users u ON u.id=t.user_id WHERE t.token_hash=? AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at>NOW()) LIMIT 1");$s->execute([$hash]);$u=$s->fetch();if(!$u||$u['user_status']!=='active')return null;$pdo=Database::connection();$today=$pdo->prepare('SELECT COUNT(*) FROM api_usage_log WHERE api_token_id=? AND created_at>=CURDATE()');$today->execute([$u['id']]);$daily=(int)$today->fetchColumn();$month=$pdo->prepare("SELECT COUNT(*) FROM api_usage_log WHERE api_token_id=? AND created_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01')");$month->execute([$u['id']]);$monthly=(int)$month->fetchColumn();header('X-RateLimit-Daily-Limit: '.(int)($u['daily_quota']??600));header('X-RateLimit-Daily-Remaining: '.max(0,(int)($u['daily_quota']??600)-$daily));header('X-RateLimit-Monthly-Limit: '.(int)($u['monthly_quota']??10000));header('X-RateLimit-Monthly-Remaining: '.max(0,(int)($u['monthly_quota']??10000)-$monthly));$warning=(int)($u['quota_warning_percent']??80);$dailyPct=((int)($u['daily_quota']??600)>0)?($daily/(int)$u['daily_quota'])*100:0;$monthlyPct=((int)($u['monthly_quota']??10000)>0)?($monthly/(int)$u['monthly_quota'])*100:0;if(max($dailyPct,$monthlyPct)>=$warning)header('X-RateLimit-Warning: quota usage is at or above '.$warning.' percent');if($daily>=(int)($u['daily_quota']??600)||$monthly>=(int)($u['monthly_quota']??10000))self::json(['error'=>'API quota exceeded'],429);$pdo->prepare('UPDATE api_tokens SET last_used_at=NOW() WHERE id=?')->execute([$u['id']]);return $u;
 }
 public static function require():array{$u=self::user();if(!$u){self::json(['error'=>'unauthorized'],401);}return $u;}
 public static function requireAbility(string $ability):array{$u=self::require();$abilities=json_decode((string)($u['abilities_json']??'[]'),true)?:[];if(!in_array('*',$abilities,true)&&!in_array($ability,$abilities,true))self::json(['error'=>'forbidden','required_ability'=>$ability],403);return $u;}
 public static function json(array $data,int $status=200):never{http_response_code($status);header('Content-Type: application/json');header('X-RateLimit-Limit: 600');header('X-RateLimit-Remaining: 599');header('X-RateLimit-Reset: '.(time()+60));echo json_encode($data,JSON_UNESCAPED_SLASHES);exit;}
}
